-- ============================================================================
-- STEP 1: Count valid interactions that will be transferred
-- ============================================================================
-- This counts interactions that:
-- 1. Don't already exist in leads_leadinteractions
-- 2. Have valid lead_id (exists in leads_lead table)

SELECT 
    COUNT(*) as valid_interactions_to_transfer
FROM 
    src_leads_leadinteractions src
WHERE 
    src.lead_id IS NOT NULL
    AND src.lead_id ~ '^[0-9]+$'  -- Only numeric lead_ids
    AND EXISTS (
        SELECT 1 
        FROM leads_lead ll 
        WHERE ll.id = CAST(src.lead_id AS bigint)
    )
    AND NOT EXISTS (
        SELECT 1 
        FROM leads_leadinteractions ll 
        WHERE 
            ll.lead_id = CAST(src.lead_id AS bigint)
            AND (src.date IS NULL OR ll.date = src.date)
            AND (src.time IS NULL OR ll.time = src.time)
            AND (src.content IS NULL OR LEFT(ll.content, 100) = LEFT(src.content, 100))
    );

-- ============================================================================
-- STEP 2: Check for invalid foreign key references
-- ============================================================================

SELECT 
    COUNT(*) as interactions_with_invalid_lead_id
FROM 
    src_leads_leadinteractions src
WHERE 
    src.lead_id IS NOT NULL
    AND src.lead_id ~ '^[0-9]+$'
    AND NOT EXISTS (
        SELECT 1 
        FROM leads_lead ll 
        WHERE ll.id = CAST(src.lead_id AS bigint)
    );

-- ============================================================================
-- STEP 3: Set sequence to start after highest existing ID
-- ============================================================================
-- This ensures new IDs don't conflict with existing ones

-- First, check the current max ID and what the next ID will be
SELECT 
    COALESCE(MAX(id), 0) as current_max_id,
    COALESCE(MAX(id), 0) + 1 as next_id_will_be,
    (SELECT last_value FROM leads_leadinteractions_id_seq) as current_sequence_value
FROM 
    leads_leadinteractions;

-- Then set the sequence to start after the highest existing ID
-- IMPORTANT: Run this BEFORE the INSERT statement in STEP 4
-- This will set the sequence to the next available ID
SELECT setval('leads_leadinteractions_id_seq', 
    (SELECT COALESCE(MAX(id), 0) + 1 FROM leads_leadinteractions), 
    false  -- false means the next nextval() will return this value (not value + 1)
);

-- ============================================================================
-- STEP 4: Transfer missing interactions from src_leads_leadinteractions to leads_leadinteractions
-- ============================================================================
-- IMPORTANT: Review the counts above and set the sequence (STEP 3) before running this INSERT statement
-- This will insert interactions that:
-- 1. Don't already exist in leads_leadinteractions
-- 2. Have valid foreign key references (lead_id exists in leads_lead)
-- Note: id field is NOT included - it will be auto-generated by the sequence

INSERT INTO leads_leadinteractions (
    cdate,
    udate,
    kind,
    date,
    time,
    minutes,
    content,
    creator_id,
    lead_id,
    direction,
    link,
    read,
    wa_num_id,
    employee_id,
    description,
    contact_id
)
SELECT 
    -- Convert cdate from text to timestamp
    CASE 
        WHEN src.cdate IS NULL OR src.cdate = '' THEN NULL
        WHEN src.cdate ~ '^\d{4}-\d{2}-\d{2}' THEN 
            -- Try to parse as date or timestamp
            CASE 
                WHEN src.cdate ~ '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}' THEN 
                    CAST(src.cdate AS timestamp with time zone)
                WHEN src.cdate ~ '^\d{4}-\d{2}-\d{2}' THEN 
                    CAST(src.cdate AS date)::timestamp with time zone
                ELSE NULL
            END
        ELSE NULL
    END as cdate,
    
    -- Convert udate from text to timestamp
    CASE 
        WHEN src.udate IS NULL OR src.udate = '' THEN NULL
        WHEN src.udate ~ '^\d{4}-\d{2}-\d{2}' THEN 
            CASE 
                WHEN src.udate ~ '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}' THEN 
                    CAST(src.udate AS timestamp with time zone)
                WHEN src.udate ~ '^\d{4}-\d{2}-\d{2}' THEN 
                    CAST(src.udate AS date)::timestamp with time zone
                ELSE NULL
            END
        ELSE NULL
    END as udate,
    
    src.kind,
    src.date,
    src.time,
    
    -- Convert minutes from text to bigint
    CASE 
        WHEN src.minutes IS NULL OR src.minutes = '' THEN NULL
        WHEN src.minutes ~ '^\d+$' THEN CAST(src.minutes AS bigint)
        ELSE NULL
    END as minutes,
    
    src.content,
    src.creator_id,
    
    -- Convert lead_id from text to bigint
    CAST(src.lead_id AS bigint) as lead_id,
    
    src.direction,
    src.link,
    src.read,
    src.wa_num_id,
    src.employee_id,
    src.description,
    
    -- Try to find contact_id from lead_leadcontact based on lead_id
    -- Use the first matching contact_id for this lead (prefer main contact if available)
    (
        SELECT llc.id
        FROM lead_leadcontact llc
        WHERE llc.lead_id = CAST(src.lead_id AS bigint)
        ORDER BY 
            CASE WHEN llc.main = 'true' THEN 1 ELSE 2 END,
            llc.id
        LIMIT 1
    ) as contact_id
    
FROM 
    src_leads_leadinteractions src
WHERE 
    src.lead_id IS NOT NULL
    AND src.lead_id ~ '^[0-9]+$'  -- Only numeric lead_ids
    -- Validate foreign keys to avoid constraint violations
    AND EXISTS (
        SELECT 1 
        FROM leads_lead ll 
        WHERE ll.id = CAST(src.lead_id AS bigint)
    )
    -- Avoid duplicates
    AND NOT EXISTS (
        SELECT 1 
        FROM leads_leadinteractions ll 
        WHERE 
            ll.lead_id = CAST(src.lead_id AS bigint)
            AND (src.date IS NULL OR ll.date = src.date)
            AND (src.time IS NULL OR ll.time = src.time)
            AND (src.content IS NULL OR LEFT(ll.content, 100) = LEFT(src.content, 100))
    );

-- ============================================================================
-- STEP 5: Verify the transfer (run after INSERT)
-- ============================================================================
-- This should now show 0 or a much smaller number

SELECT 
    COUNT(*) as still_missing_interactions_count
FROM 
    src_leads_leadinteractions src
WHERE 
    src.lead_id IS NOT NULL
    AND src.lead_id ~ '^[0-9]+$'
    AND EXISTS (
        SELECT 1 
        FROM leads_lead ll 
        WHERE ll.id = CAST(src.lead_id AS bigint)
    )
    AND NOT EXISTS (
        SELECT 1 
        FROM leads_leadinteractions ll 
        WHERE 
            ll.lead_id = CAST(src.lead_id AS bigint)
            AND (src.date IS NULL OR ll.date = src.date)
            AND (src.time IS NULL OR ll.time = src.time)
            AND (src.content IS NULL OR LEFT(ll.content, 100) = LEFT(src.content, 100))
    );

-- ============================================================================
-- STEP 6: List excluded interactions (cannot be transferred)
-- ============================================================================
-- This shows interactions that cannot be transferred and why

SELECT 
    src.id as src_id,
    src.lead_id,
    src.date,
    src.time,
    src.kind,
    LEFT(src.content, 50) as content_preview,
    CASE 
        WHEN src.lead_id IS NULL THEN 'No lead_id'
        WHEN src.lead_id !~ '^[0-9]+$' THEN 'Non-numeric lead_id'
        WHEN NOT EXISTS (SELECT 1 FROM leads_lead ll WHERE ll.id = CAST(src.lead_id AS bigint))
        THEN 'Invalid lead_id (not in leads_lead)'
        WHEN EXISTS (
            SELECT 1 
            FROM leads_leadinteractions ll 
            WHERE 
                ll.lead_id = CAST(src.lead_id AS bigint)
                AND (src.date IS NULL OR ll.date = src.date)
                AND (src.time IS NULL OR ll.time = src.time)
                AND (src.content IS NULL OR LEFT(ll.content, 100) = LEFT(src.content, 100))
        )
        THEN 'Already exists'
        ELSE 'Other reason'
    END as exclusion_reason
FROM 
    src_leads_leadinteractions src
WHERE 
    src.lead_id IS NOT NULL
    AND (
        src.lead_id !~ '^[0-9]+$'
        OR NOT EXISTS (SELECT 1 FROM leads_lead ll WHERE ll.id = CAST(src.lead_id AS bigint))
        OR EXISTS (
            SELECT 1 
            FROM leads_leadinteractions ll 
            WHERE 
                ll.lead_id = CAST(src.lead_id AS bigint)
                AND (src.date IS NULL OR ll.date = src.date)
                AND (src.time IS NULL OR ll.time = src.time)
                AND (src.content IS NULL OR LEFT(ll.content, 100) = LEFT(src.content, 100))
        )
    )
ORDER BY 
    CASE 
        WHEN src.lead_id ~ '^[0-9]+$' THEN CAST(src.lead_id AS bigint)
        ELSE 0
    END,
    src.date,
    src.time
LIMIT 100;
