-- Create webhook_settings table
CREATE TABLE IF NOT EXISTS public.webhook_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_active BOOLEAN NOT NULL DEFAULT true,
  last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Add RLS policies
ALTER TABLE public.webhook_settings ENABLE ROW LEVEL SECURITY;

-- Policy: Allow superusers to read webhook settings
CREATE POLICY "Allow superusers to read webhook settings"
ON public.webhook_settings
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE users.auth_id = auth.uid()
    AND users.is_superuser = true
  )
);

-- Policy: Allow superusers to insert webhook settings
CREATE POLICY "Allow superusers to insert webhook settings"
ON public.webhook_settings
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE users.auth_id = auth.uid()
    AND users.is_superuser = true
  )
);

-- Policy: Allow superusers to update webhook settings
CREATE POLICY "Allow superusers to update webhook settings"
ON public.webhook_settings
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE users.auth_id = auth.uid()
    AND users.is_superuser = true
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.users
    WHERE users.auth_id = auth.uid()
    AND users.is_superuser = true
  )
);

-- Insert default record (webhook active by default)
INSERT INTO public.webhook_settings (is_active, last_updated, updated_by)
VALUES (true, NOW(), 'System')
ON CONFLICT DO NOTHING;

-- Add comment to table
COMMENT ON TABLE public.webhook_settings IS 'Controls whether the webhook endpoint (/api/hook/catch) accepts new lead data';

