-- Per-lead document type columns for CRM Documents tab (not all types shown by default).
-- Run in Supabase SQL editor.

CREATE TABLE IF NOT EXISTS public.lead_case_document_type_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_number TEXT NOT NULL,
  document_type_id UUID NOT NULL REFERENCES public.lead_case_document_types(id) ON DELETE CASCADE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT lead_case_document_type_assignments_unique UNIQUE (lead_number, document_type_id)
);

CREATE INDEX IF NOT EXISTS idx_lead_case_document_type_assignments_lead_number
  ON public.lead_case_document_type_assignments(lead_number);

ALTER TABLE public.lead_case_document_type_assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS lead_case_document_type_assignments_authenticated_all
  ON public.lead_case_document_type_assignments;
CREATE POLICY lead_case_document_type_assignments_authenticated_all
  ON public.lead_case_document_type_assignments
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.lead_case_document_type_assignments TO authenticated;
