-- Snapshot prior clock-in state when an employee edits a session and it re-enters approval.
-- Run after employee_clock_in approval / location migrations.

CREATE TABLE IF NOT EXISTS public.employee_clock_in_revisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    clock_in_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    revision_source text NOT NULL CHECK (revision_source IN ('automatic', 'manual')),
    clock_in_time timestamp with time zone NOT NULL,
    clock_out_time timestamp with time zone,
    notes text,
    manually boolean,
    approved boolean,
    declined boolean,
    clock_in_location_id bigint,
    clock_out_location_id bigint,
    location_latitude numeric(10, 8),
    location_longitude numeric(11, 8),
    location_address text,
    location_city text,
    location_country text,
    location_source text,
    clock_out_location_latitude numeric(10, 8),
    clock_out_location_longitude numeric(11, 8),
    clock_out_location_address text,
    clock_out_location_city text,
    clock_out_location_country text,
    clock_out_location_source text,
    CONSTRAINT employee_clock_in_revisions_pkey PRIMARY KEY (id),
    CONSTRAINT employee_clock_in_revisions_clock_in_id_fkey
        FOREIGN KEY (clock_in_id) REFERENCES public.employee_clock_in(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_employee_clock_in_revisions_clock_in_id_created
    ON public.employee_clock_in_revisions(clock_in_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_employee_clock_in_revisions_employee_id
    ON public.employee_clock_in_revisions(employee_id);

COMMENT ON TABLE public.employee_clock_in_revisions IS
    'Previous clock-in snapshot saved before employee edits that require re-approval';

ALTER TABLE public.employee_clock_in_revisions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Superusers can read clock-in revisions" ON public.employee_clock_in_revisions;
CREATE POLICY "Superusers can read clock-in revisions"
ON public.employee_clock_in_revisions FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.auth_id = auth.uid()
        AND (
            u.is_superuser IS TRUE
            OR u.is_superuser::text IN ('true', 't', '1')
            OR u.role = 'admin'
            OR u.is_staff IS TRUE
        )
    )
);

DROP POLICY IF EXISTS "Employees can read own clock-in revisions" ON public.employee_clock_in_revisions;
CREATE POLICY "Employees can read own clock-in revisions"
ON public.employee_clock_in_revisions FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.auth_id = auth.uid()
        AND u.employee_id = employee_clock_in_revisions.employee_id
    )
);

DROP POLICY IF EXISTS "System can insert clock-in revisions" ON public.employee_clock_in_revisions;
CREATE POLICY "System can insert clock-in revisions"
ON public.employee_clock_in_revisions FOR INSERT
TO authenticated
WITH CHECK (true);
