-- Registry of expenses created from Finance → Expenses.
-- Destination rows still live in lead_expenses / lead_subcontractor_fees /
-- firm_management_costs / office_expenses / source_media_expense.

CREATE OR REPLACE FUNCTION public.is_app_superuser()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
      )
  );
$$;

CREATE TABLE IF NOT EXISTS public.finance_expense_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  kind text NOT NULL
    CHECK (kind IN ('lead', 'subcontractor', 'other_firm', 'office', 'marketing')),

  destination_table text NOT NULL,
  destination_id text NOT NULL,

  expense_date date,
  amount numeric(14, 2) NOT NULL CHECK (amount >= 0),
  currency_code text,

  firm_id uuid REFERENCES public.firms (id) ON DELETE SET NULL,
  new_lead_id uuid REFERENCES public.leads (id) ON DELETE SET NULL,
  legacy_lead_id bigint REFERENCES public.leads_lead (id) ON DELETE SET NULL,

  category_label text,
  vendor_label text,
  notes text,

  created_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,

  CONSTRAINT finance_expense_entries_one_lead CHECK (
    NOT (new_lead_id IS NOT NULL AND legacy_lead_id IS NOT NULL)
  ),
  CONSTRAINT finance_expense_entries_destination_key UNIQUE (destination_table, destination_id)
);

CREATE INDEX IF NOT EXISTS idx_finance_expense_entries_kind_date
  ON public.finance_expense_entries (kind, expense_date DESC);

CREATE INDEX IF NOT EXISTS idx_finance_expense_entries_created_at
  ON public.finance_expense_entries (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_finance_expense_entries_firm
  ON public.finance_expense_entries (firm_id)
  WHERE firm_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_finance_expense_entries_new_lead
  ON public.finance_expense_entries (new_lead_id)
  WHERE new_lead_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_finance_expense_entries_legacy_lead
  ON public.finance_expense_entries (legacy_lead_id)
  WHERE legacy_lead_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_finance_expense_entries_created_by
  ON public.finance_expense_entries (created_by)
  WHERE created_by IS NOT NULL;

COMMENT ON TABLE public.finance_expense_entries IS
  'Index of expenses created from Finance → Expenses. Source of truth remains the destination tables.';

DROP TRIGGER IF EXISTS tr_finance_expense_entries_updated_at ON public.finance_expense_entries;
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'firms_touch_updated_at'
  ) THEN
    CREATE TRIGGER tr_finance_expense_entries_updated_at
      BEFORE UPDATE ON public.finance_expense_entries
      FOR EACH ROW
      EXECUTE FUNCTION public.firms_touch_updated_at();
  END IF;
END
$$;

ALTER TABLE public.finance_expense_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "finance_expense_entries_select" ON public.finance_expense_entries;
CREATE POLICY "finance_expense_entries_select"
  ON public.finance_expense_entries
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "finance_expense_entries_insert" ON public.finance_expense_entries;
CREATE POLICY "finance_expense_entries_insert"
  ON public.finance_expense_entries
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL AND (created_by IS NULL OR created_by = auth.uid()));

DROP POLICY IF EXISTS "finance_expense_entries_update" ON public.finance_expense_entries;
CREATE POLICY "finance_expense_entries_update"
  ON public.finance_expense_entries
  FOR UPDATE
  TO authenticated
  USING (created_by = auth.uid() OR public.is_app_superuser())
  WITH CHECK (created_by = auth.uid() OR public.is_app_superuser());

DROP POLICY IF EXISTS "finance_expense_entries_delete" ON public.finance_expense_entries;
CREATE POLICY "finance_expense_entries_delete"
  ON public.finance_expense_entries
  FOR DELETE
  TO authenticated
  USING (created_by = auth.uid() OR public.is_app_superuser());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.finance_expense_entries TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.finance_expense_entries_id_seq TO authenticated;
