-- Employee roles catalog (id PK) + FK from tenants_employee.
-- Shared client helpers: src/lib/employeeRoles.ts
-- Admin UI: EmployeeRolesManager

-- Recreate catalog (safe if prior code-PK version was applied)
DROP TABLE IF EXISTS public.employee_roles CASCADE;

CREATE TABLE public.employee_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 100,
  is_selectable boolean NOT NULL DEFAULT true,
  alias_of_id bigint NULL REFERENCES public.employee_roles (id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT employee_roles_code_unique UNIQUE (code),
  CONSTRAINT employee_roles_name_not_blank CHECK (char_length(trim(name)) > 0),
  CONSTRAINT employee_roles_code_not_blank CHECK (char_length(trim(code)) > 0),
  CONSTRAINT employee_roles_alias_not_self CHECK (alias_of_id IS NULL OR alias_of_id <> id)
);

CREATE INDEX idx_employee_roles_selectable
  ON public.employee_roles (is_selectable, sort_order)
  WHERE is_active;

CREATE INDEX idx_employee_roles_alias_of_id
  ON public.employee_roles (alias_of_id)
  WHERE alias_of_id IS NOT NULL;

CREATE INDEX idx_employee_roles_active_name
  ON public.employee_roles (is_active, name);

COMMENT ON TABLE public.employee_roles IS
  'Catalog of employee bonuses/org roles. tenants_employee.bonuses_role_id → employee_roles.id; bonuses_role text stays synced to code.';

-- Canonical roles
INSERT INTO public.employee_roles (code, name, sort_order, is_selectable, alias_of_id) VALUES
  ('One-time bonus (temporary)', 'One-time bonus (temporary)', 10, true, NULL),
  ('No bonuses', 'No bonuses', 20, true, NULL),
  ('c', 'Closer', 30, true, NULL),
  ('s', 'Scheduler', 40, true, NULL),
  ('h', 'Handler', 50, true, NULL),
  ('e', 'Expert', 60, true, NULL),
  ('z', 'Manager', 70, true, NULL),
  ('m', 'Manager', 75, true, NULL),
  ('p', 'Partner', 80, true, NULL),
  ('dm', 'Department Manager', 90, true, NULL),
  ('pm', 'Project Manager', 100, true, NULL),
  ('om', 'Office Manager', 110, true, NULL),
  ('se', 'Secretary', 120, true, NULL),
  ('b', 'Book keeper', 130, true, NULL),
  ('partners', 'Partners', 140, true, NULL),
  ('dv', 'Developer', 150, true, NULL),
  ('ma', 'Marketing', 160, true, NULL),
  ('f', 'Finance', 170, true, NULL),
  ('col', 'Collection', 180, true, NULL),
  ('d', 'Diverse', 190, true, NULL),
  ('lawyer', 'Helper Closer', 200, true, NULL),
  ('n', 'No role', 210, true, NULL);

-- Legacy aliases (point at canonical id by code)
INSERT INTO public.employee_roles (code, name, sort_order, is_selectable, alias_of_id)
SELECT v.code, v.name, v.sort_order, false, r.id
FROM (
  VALUES
    ('Z', 'Manager', 71, 'z'),
    ('M', 'Manager', 76, 'm'),
    ('P', 'Partner', 81, 'p'),
    ('DM', 'Department Manager', 91, 'dm'),
    ('PM', 'Project Manager', 101, 'pm'),
    ('OM', 'Office Manager', 111, 'om'),
    ('SE', 'Secretary', 121, 'se'),
    ('B', 'Book keeper', 131, 'b'),
    ('Partners', 'Partners', 141, 'partners'),
    ('helper-closer', 'Helper Closer', 201, 'lawyer')
) AS v(code, name, sort_order, canonical_code)
JOIN public.employee_roles r ON r.code = v.canonical_code;

-- Link employees → roles
ALTER TABLE public.tenants_employee
  ADD COLUMN IF NOT EXISTS bonuses_role_id bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'tenants_employee_bonuses_role_id_fkey'
  ) THEN
    ALTER TABLE public.tenants_employee
      ADD CONSTRAINT tenants_employee_bonuses_role_id_fkey
      FOREIGN KEY (bonuses_role_id)
      REFERENCES public.employee_roles (id)
      ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tenants_employee_bonuses_role_id
  ON public.tenants_employee (bonuses_role_id);

-- Backfill role ids from existing text codes (exact, then lower)
UPDATE public.tenants_employee te
SET bonuses_role_id = r.id
FROM public.employee_roles r
WHERE te.bonuses_role_id IS NULL
  AND te.bonuses_role IS NOT NULL
  AND trim(te.bonuses_role) <> ''
  AND r.code = trim(te.bonuses_role);

UPDATE public.tenants_employee te
SET bonuses_role_id = r.id
FROM public.employee_roles r
WHERE te.bonuses_role_id IS NULL
  AND te.bonuses_role IS NOT NULL
  AND trim(te.bonuses_role) <> ''
  AND lower(r.code) = lower(trim(te.bonuses_role));

-- Keep bonuses_role text in sync with selected role id (legacy readers keep working)
CREATE OR REPLACE FUNCTION public.sync_tenants_employee_bonuses_role_from_id()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.bonuses_role_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT r.code
    INTO NEW.bonuses_role
  FROM public.employee_roles r
  WHERE r.id = NEW.bonuses_role_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_tenants_employee_bonuses_role ON public.tenants_employee;
CREATE TRIGGER trg_sync_tenants_employee_bonuses_role
  BEFORE INSERT OR UPDATE OF bonuses_role_id
  ON public.tenants_employee
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_tenants_employee_bonuses_role_from_id();

-- If only text role is written, resolve id when possible
CREATE OR REPLACE FUNCTION public.sync_tenants_employee_bonuses_role_id_from_code()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.bonuses_role_id IS NOT NULL THEN
    RETURN NEW;
  END IF;
  IF NEW.bonuses_role IS NULL OR trim(NEW.bonuses_role) = '' THEN
    RETURN NEW;
  END IF;

  SELECT r.id
    INTO NEW.bonuses_role_id
  FROM public.employee_roles r
  WHERE r.code = trim(NEW.bonuses_role)
     OR lower(r.code) = lower(trim(NEW.bonuses_role))
  ORDER BY CASE WHEN r.code = trim(NEW.bonuses_role) THEN 0 ELSE 1 END
  LIMIT 1;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_tenants_employee_bonuses_role_id ON public.tenants_employee;
CREATE TRIGGER trg_sync_tenants_employee_bonuses_role_id
  BEFORE INSERT OR UPDATE OF bonuses_role
  ON public.tenants_employee
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_tenants_employee_bonuses_role_id_from_code();

ALTER TABLE public.employee_roles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS employee_roles_select_authenticated ON public.employee_roles;
CREATE POLICY employee_roles_select_authenticated
  ON public.employee_roles
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS employee_roles_select_anon ON public.employee_roles;
CREATE POLICY employee_roles_select_anon
  ON public.employee_roles
  FOR SELECT
  TO anon
  USING (true);

DROP POLICY IF EXISTS employee_roles_write_authenticated ON public.employee_roles;
CREATE POLICY employee_roles_write_authenticated
  ON public.employee_roles
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT ON public.employee_roles TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.employee_roles TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.employee_roles_id_seq TO authenticated;
