-- Lead employee budget extension requests:
-- Employees request more time/budget when a lead is over the employee-cost cap.
-- Approving adds to max allowed cost without changing lead value.

CREATE TABLE IF NOT EXISTS public.lead_employee_budget_extension_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  -- Lead identity (same pattern as allocation items)
  lead_type text CHECK (lead_type IS NULL OR lead_type IN ('new', 'legacy')),
  new_lead_id uuid,
  legacy_lead_id bigint,
  lead_number text,
  client_name text,

  -- Requester
  employee_id bigint NOT NULL REFERENCES public.tenants_employee(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Requested additional capacity
  requested_extra_ms bigint NOT NULL CHECK (requested_extra_ms > 0),
  requested_extra_cost_nis numeric(12, 2) NOT NULL CHECK (requested_extra_cost_nis >= 0),
  request_reason text NOT NULL CHECK (length(btrim(request_reason)) > 0),

  -- Snapshot at request time (for management context)
  cost_at_request_nis numeric(12, 2),
  max_at_request_nis numeric(12, 2),
  worked_ms_at_request bigint,

  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'declined')),

  -- Review
  review_note text,
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_by_employee_id bigint REFERENCES public.tenants_employee(id) ON DELETE SET NULL,
  reviewed_at timestamptz,

  -- When approved, this amount is added to the lead's employee-cost max
  approved_extra_cost_nis numeric(12, 2)
);

CREATE INDEX IF NOT EXISTS idx_lead_budget_ext_req_status
  ON public.lead_employee_budget_extension_requests (status);

CREATE INDEX IF NOT EXISTS idx_lead_budget_ext_req_new_lead
  ON public.lead_employee_budget_extension_requests (new_lead_id)
  WHERE new_lead_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_budget_ext_req_legacy_lead
  ON public.lead_employee_budget_extension_requests (legacy_lead_id)
  WHERE legacy_lead_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_budget_ext_req_lead_number
  ON public.lead_employee_budget_extension_requests (lead_number)
  WHERE lead_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_budget_ext_req_employee
  ON public.lead_employee_budget_extension_requests (employee_id);

CREATE INDEX IF NOT EXISTS idx_lead_budget_ext_req_pending
  ON public.lead_employee_budget_extension_requests (status)
  WHERE status = 'pending';

COMMENT ON TABLE public.lead_employee_budget_extension_requests IS
  'Requests for extra employee-cost budget/time on a lead; approved extras raise the max without changing lead value.';

ALTER TABLE public.lead_employee_budget_extension_requests ENABLE ROW LEVEL SECURITY;

-- Employees: view own requests
DROP POLICY IF EXISTS "Employees can view own lead budget extension requests"
  ON public.lead_employee_budget_extension_requests;
CREATE POLICY "Employees can view own lead budget extension requests"
ON public.lead_employee_budget_extension_requests FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND u.employee_id = lead_employee_budget_extension_requests.employee_id
  )
);

-- Superusers: view all
DROP POLICY IF EXISTS "Superusers can view all lead budget extension requests"
  ON public.lead_employee_budget_extension_requests;
CREATE POLICY "Superusers can view all lead budget extension requests"
ON public.lead_employee_budget_extension_requests FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
      )
  )
);

-- Employees: insert own pending
DROP POLICY IF EXISTS "Employees can insert own lead budget extension requests"
  ON public.lead_employee_budget_extension_requests;
CREATE POLICY "Employees can insert own lead budget extension requests"
ON public.lead_employee_budget_extension_requests FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() = user_id
  AND status = 'pending'
  AND EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND u.employee_id = lead_employee_budget_extension_requests.employee_id
  )
);

-- Superusers: update (approve/decline)
DROP POLICY IF EXISTS "Superusers can update lead budget extension requests"
  ON public.lead_employee_budget_extension_requests;
CREATE POLICY "Superusers can update lead budget extension requests"
ON public.lead_employee_budget_extension_requests FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
      )
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
      )
  )
);

GRANT SELECT, INSERT, UPDATE ON public.lead_employee_budget_extension_requests TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.lead_employee_budget_extension_requests_id_seq TO authenticated;
