-- Work-from-home period requests: employees request a day or date range;
-- admins approve/decline. Approved periods allow Home clock-in without permanent works_from_home.

CREATE TABLE IF NOT EXISTS public.employee_wfh_period_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  employee_id bigint NOT NULL REFERENCES public.tenants_employee(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'declined')),
  notes text,
  decline_note text,
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  CONSTRAINT employee_wfh_period_requests_dates_check CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_employee_wfh_period_requests_employee_id
  ON public.employee_wfh_period_requests (employee_id);

CREATE INDEX IF NOT EXISTS idx_employee_wfh_period_requests_status
  ON public.employee_wfh_period_requests (status);

CREATE INDEX IF NOT EXISTS idx_employee_wfh_period_requests_dates
  ON public.employee_wfh_period_requests (start_date, end_date);

CREATE INDEX IF NOT EXISTS idx_employee_wfh_period_requests_pending
  ON public.employee_wfh_period_requests (status)
  WHERE status = 'pending';

COMMENT ON TABLE public.employee_wfh_period_requests IS
  'Employee requests to work from home for a date range; approval grants Home clock-in only for that period.';

ALTER TABLE public.employee_wfh_period_requests ENABLE ROW LEVEL SECURITY;

-- Employees can view their own requests
DROP POLICY IF EXISTS "Employees can view own WFH period requests"
  ON public.employee_wfh_period_requests;
CREATE POLICY "Employees can view own WFH period requests"
ON public.employee_wfh_period_requests FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND u.employee_id = employee_wfh_period_requests.employee_id
  )
);

-- Admins/superusers can view all
DROP POLICY IF EXISTS "Admins can view all WFH period requests"
  ON public.employee_wfh_period_requests;
CREATE POLICY "Admins can view all WFH period requests"
ON public.employee_wfh_period_requests FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
        OR u.role = 'admin'
      )
  )
);

-- Employees can insert their own pending requests
DROP POLICY IF EXISTS "Employees can insert own WFH period requests"
  ON public.employee_wfh_period_requests;
CREATE POLICY "Employees can insert own WFH period requests"
ON public.employee_wfh_period_requests FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() = user_id
  AND status = 'pending'
  AND EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND u.employee_id = employee_wfh_period_requests.employee_id
  )
);

-- Admins can update (approve/decline)
DROP POLICY IF EXISTS "Admins can update WFH period requests"
  ON public.employee_wfh_period_requests;
CREATE POLICY "Admins can update WFH period requests"
ON public.employee_wfh_period_requests FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
        OR u.role = 'admin'
      )
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
        OR u.role = 'admin'
      )
  )
);

GRANT SELECT, INSERT, UPDATE ON public.employee_wfh_period_requests TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.employee_wfh_period_requests_id_seq TO authenticated;
