-- Dedicated price-offer history. Offer tabs must NOT query public.emails (5M+ rows).
-- Safe to re-run.

CREATE TABLE IF NOT EXISTS public.lead_price_offers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid NULL,
  legacy_id bigint NULL,
  body text NOT NULL,
  sender_name text NULL,
  sender_email text NULL,
  total numeric NULL,
  currency text NULL,
  email_message_id text NULL,
  sent_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lead_price_offers_lead_chk CHECK (client_id IS NOT NULL OR legacy_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS lead_price_offers_client_sent_idx
  ON public.lead_price_offers (client_id, sent_at ASC)
  WHERE client_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS lead_price_offers_legacy_sent_idx
  ON public.lead_price_offers (legacy_id, sent_at ASC)
  WHERE legacy_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS lead_price_offers_email_message_id_key
  ON public.lead_price_offers (email_message_id)
  WHERE email_message_id IS NOT NULL;

ALTER TABLE public.lead_price_offers ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT ON public.lead_price_offers TO authenticated;
GRANT ALL ON public.lead_price_offers TO service_role;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'S'
      AND c.relname = 'lead_price_offers_id_seq'
  ) THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public.lead_price_offers_id_seq TO authenticated, service_role';
  END IF;
END $$;

DROP POLICY IF EXISTS "staff_select_lead_price_offers" ON public.lead_price_offers;
CREATE POLICY "staff_select_lead_price_offers"
  ON public.lead_price_offers
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "staff_insert_lead_price_offers" ON public.lead_price_offers;
CREATE POLICY "staff_insert_lead_price_offers"
  ON public.lead_price_offers
  FOR INSERT
  TO authenticated
  WITH CHECK (client_id IS NOT NULL OR legacy_id IS NOT NULL);

-- One-time copy of already-saved offer_* email rows into this table (index range, not a full scan).
INSERT INTO public.lead_price_offers (
  client_id,
  legacy_id,
  body,
  sender_name,
  sender_email,
  email_message_id,
  sent_at
)
SELECT
  e.client_id,
  e.legacy_id,
  COALESCE(
    NULLIF(BTRIM(e.body_preview), ''),
    NULLIF(BTRIM(e.body_html), ''),
    '(no offer text)'
  ),
  e.sender_name,
  e.sender_email,
  e.message_id,
  COALESCE(e.sent_at, now())
FROM public.emails e
WHERE e.message_id >= 'offer_'
  AND e.message_id < 'offer`'
  AND (e.client_id IS NOT NULL OR e.legacy_id IS NOT NULL)
  AND NOT EXISTS (
    SELECT 1
    FROM public.lead_price_offers p
    WHERE p.email_message_id = e.message_id
  );
