-- Multiple invoices/receipts per Finance → Expenses registry row.
-- Run after sql/2026-08-17_finance_expense_entries.sql

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'finance-expense-documents',
  'finance-expense-documents',
  false,
  15728640,
  ARRAY[
    'image/jpeg',
    'image/jpg',
    'image/png',
    'image/gif',
    'image/webp',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-excel'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = 15728640,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "finance-expense-documents insert" ON storage.objects;
DROP POLICY IF EXISTS "finance-expense-documents select" ON storage.objects;
DROP POLICY IF EXISTS "finance-expense-documents update" ON storage.objects;
DROP POLICY IF EXISTS "finance-expense-documents delete" ON storage.objects;

CREATE POLICY "finance-expense-documents insert" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'finance-expense-documents');

CREATE POLICY "finance-expense-documents select" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'finance-expense-documents');

CREATE POLICY "finance-expense-documents update" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'finance-expense-documents')
  WITH CHECK (bucket_id = 'finance-expense-documents');

CREATE POLICY "finance-expense-documents delete" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'finance-expense-documents');

CREATE TABLE IF NOT EXISTS public.finance_expense_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  entry_id bigint NOT NULL REFERENCES public.finance_expense_entries (id) ON DELETE CASCADE,
  document_type text NOT NULL DEFAULT 'invoice'
    CHECK (document_type IN ('invoice', 'receipt', 'other')),
  file_name text NOT NULL,
  mime_type text,
  storage_path text NOT NULL,
  uploaded_by uuid REFERENCES auth.users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_finance_expense_documents_entry
  ON public.finance_expense_documents (entry_id, created_at DESC);

COMMENT ON TABLE public.finance_expense_documents IS
  'Invoices, receipts, and other files attached to a Finance → Expenses row. Multiple files per expense.';

ALTER TABLE public.finance_expense_documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "finance_expense_documents_select" ON public.finance_expense_documents;
CREATE POLICY "finance_expense_documents_select"
  ON public.finance_expense_documents
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "finance_expense_documents_insert" ON public.finance_expense_documents;
CREATE POLICY "finance_expense_documents_insert"
  ON public.finance_expense_documents
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() IS NOT NULL AND (uploaded_by IS NULL OR uploaded_by = auth.uid()));

DROP POLICY IF EXISTS "finance_expense_documents_delete" ON public.finance_expense_documents;
CREATE POLICY "finance_expense_documents_delete"
  ON public.finance_expense_documents
  FOR DELETE TO authenticated
  USING (uploaded_by = auth.uid() OR public.is_app_superuser());

GRANT SELECT, INSERT, DELETE ON public.finance_expense_documents TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.finance_expense_documents_id_seq TO authenticated;
