-- Proper many-to-many link: sub_efforts <-> misc_category (replaces misc_category_id on sub_efforts).
-- Run AFTER 2026-07-09_sub_efforts_misc_category_and_sort_order.sql if that was applied.
-- Cleans duplicated sub_efforts rows and seeds all category links in the junction table.

-- ---------------------------------------------------------------------------
-- 1) Junction table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sub_effort_misc_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sub_effort_id bigint NOT NULL,
  misc_category_id integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sub_effort_misc_categories_pkey PRIMARY KEY (id),
  CONSTRAINT sub_effort_misc_categories_sub_effort_id_fkey
    FOREIGN KEY (sub_effort_id) REFERENCES public.sub_efforts (id) ON DELETE CASCADE,
  CONSTRAINT sub_effort_misc_categories_misc_category_id_fkey
    FOREIGN KEY (misc_category_id) REFERENCES public.misc_category (id) ON DELETE CASCADE,
  CONSTRAINT sub_effort_misc_categories_unique_pair UNIQUE (sub_effort_id, misc_category_id)
);

COMMENT ON TABLE public.sub_effort_misc_categories IS
  'Links sub effort templates to case types (misc_category). Many-to-many.';

CREATE INDEX IF NOT EXISTS idx_sub_effort_misc_categories_sub_effort_id
  ON public.sub_effort_misc_categories USING btree (sub_effort_id);

CREATE INDEX IF NOT EXISTS idx_sub_effort_misc_categories_misc_category_id
  ON public.sub_effort_misc_categories USING btree (misc_category_id);

-- ---------------------------------------------------------------------------
-- 2) Pick one canonical sub_efforts row per name; map duplicates -> canonical
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE _sub_effort_canonical ON COMMIT DROP AS
SELECT DISTINCT ON (lower(trim(name)))
  id AS canonical_id,
  lower(trim(name)) AS name_key,
  trim(name) AS name
FROM public.sub_efforts
ORDER BY
  lower(trim(name)),
  CASE WHEN misc_category_id IS NULL THEN 0 ELSE 1 END,
  (
    SELECT COUNT(*)::bigint
    FROM public.lead_sub_efforts lse
    WHERE lse.sub_effort_id = sub_efforts.id
  ) DESC,
  id ASC;

CREATE TEMP TABLE _sub_effort_id_map ON COMMIT DROP AS
SELECT
  se.id AS old_id,
  c.canonical_id
FROM public.sub_efforts se
INNER JOIN _sub_effort_canonical c ON lower(trim(se.name)) = c.name_key;

-- ---------------------------------------------------------------------------
-- 3) Repoint FKs from duplicate rows to canonical
-- ---------------------------------------------------------------------------
UPDATE public.lead_sub_efforts AS lse
SET sub_effort_id = m.canonical_id
FROM _sub_effort_id_map m
WHERE lse.sub_effort_id = m.old_id
  AND m.old_id <> m.canonical_id;

-- Remove duplicate lead_sub_efforts after repointing (same lead + same sub effort).
DELETE FROM public.lead_sub_efforts a
USING public.lead_sub_efforts b
WHERE a.id > b.id
  AND a.sub_effort_id = b.sub_effort_id
  AND COALESCE(a.new_lead_id::text, 'legacy:' || a.legacy_lead_id::text)
    = COALESCE(b.new_lead_id::text, 'legacy:' || b.legacy_lead_id::text);

UPDATE public.sub_category_efforts AS sce
SET sub_effort_id = m.canonical_id
FROM _sub_effort_id_map m
WHERE sce.sub_effort_id = m.old_id
  AND m.old_id <> m.canonical_id;

-- ---------------------------------------------------------------------------
-- 4) Populate junction from existing misc_category_id duplicates (if column exists)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'sub_efforts'
      AND column_name = 'misc_category_id'
  ) THEN
    INSERT INTO public.sub_effort_misc_categories (sub_effort_id, misc_category_id)
    SELECT DISTINCT m.canonical_id, se.misc_category_id
    FROM public.sub_efforts se
    INNER JOIN _sub_effort_id_map m ON m.old_id = se.id
    WHERE se.misc_category_id IS NOT NULL
    ON CONFLICT (sub_effort_id, misc_category_id) DO NOTHING;
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- 5) Connect every canonical sub effort to every misc_category
-- ---------------------------------------------------------------------------
INSERT INTO public.sub_effort_misc_categories (sub_effort_id, misc_category_id)
SELECT c.canonical_id, mc.id
FROM _sub_effort_canonical c
CROSS JOIN public.misc_category mc
ON CONFLICT (sub_effort_id, misc_category_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 6) Delete duplicate sub_efforts rows (keep canonical only)
-- ---------------------------------------------------------------------------
DELETE FROM public.sub_efforts se
USING _sub_effort_id_map m
WHERE se.id = m.old_id
  AND m.old_id <> m.canonical_id;

-- ---------------------------------------------------------------------------
-- 7) Drop misc_category_id from sub_efforts (wrong model)
-- ---------------------------------------------------------------------------
ALTER TABLE public.sub_efforts
  DROP CONSTRAINT IF EXISTS sub_efforts_misc_category_id_fkey;

DROP INDEX IF EXISTS public.idx_sub_efforts_misc_category_id;
DROP INDEX IF EXISTS public.idx_sub_efforts_misc_category_sort_order;
DROP INDEX IF EXISTS public.sub_efforts_misc_category_id_name_key;
DROP INDEX IF EXISTS public.sub_efforts_name_global_key;

ALTER TABLE public.sub_efforts
  DROP COLUMN IF EXISTS misc_category_id;

-- Restore one row per sub-effort name globally.
ALTER TABLE public.sub_efforts
  DROP CONSTRAINT IF EXISTS sub_efforts_name_key;

CREATE UNIQUE INDEX IF NOT EXISTS sub_efforts_name_key
  ON public.sub_efforts (lower(trim(name)));

-- ---------------------------------------------------------------------------
-- 8) RLS
-- ---------------------------------------------------------------------------
ALTER TABLE public.sub_effort_misc_categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sub_effort_misc_categories_authenticated_select" ON public.sub_effort_misc_categories;
DROP POLICY IF EXISTS "sub_effort_misc_categories_authenticated_insert" ON public.sub_effort_misc_categories;
DROP POLICY IF EXISTS "sub_effort_misc_categories_authenticated_update" ON public.sub_effort_misc_categories;
DROP POLICY IF EXISTS "sub_effort_misc_categories_authenticated_delete" ON public.sub_effort_misc_categories;

CREATE POLICY "sub_effort_misc_categories_authenticated_select" ON public.sub_effort_misc_categories
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "sub_effort_misc_categories_authenticated_insert" ON public.sub_effort_misc_categories
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "sub_effort_misc_categories_authenticated_update" ON public.sub_effort_misc_categories
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "sub_effort_misc_categories_authenticated_delete" ON public.sub_effort_misc_categories
  FOR DELETE TO authenticated USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.sub_effort_misc_categories TO authenticated;

DO $$
BEGIN
  GRANT USAGE, SELECT ON SEQUENCE public.sub_effort_misc_categories_id_seq TO authenticated;
EXCEPTION
  WHEN undefined_table OR invalid_schema_name THEN
    NULL;
END;
$$;
