-- Persist Graph email attachments so any staff member can open them later.
-- Graph item IDs are mailbox-specific; workers sync other people's mail and cannot
-- re-download those files from their own mailbox. Copy bytes into Storage once
-- while the owning mailbox token is available.
--
-- Access: bucket is PRIVATE. Backend uses the service role. The CRM reads files
-- only through GET /api/emails/:id/attachments/:attachmentId.
--
-- If the bucket INSERT fails, create "email-attachments" in the Dashboard
-- (Private, 25 MB file limit).
--
-- Safe to re-run: the table may already exist from an older schema.

CREATE TABLE IF NOT EXISTS public.email_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email_id bigint,
  message_id text,
  graph_attachment_id text,
  name text,
  content_type text,
  size_bytes bigint,
  is_inline boolean NOT NULL DEFAULT false,
  content_id text,
  storage_path text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.email_attachments
  ADD COLUMN IF NOT EXISTS email_id bigint,
  ADD COLUMN IF NOT EXISTS message_id text,
  ADD COLUMN IF NOT EXISTS graph_attachment_id text,
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS content_type text,
  ADD COLUMN IF NOT EXISTS size_bytes bigint,
  ADD COLUMN IF NOT EXISTS is_inline boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS content_id text,
  ADD COLUMN IF NOT EXISTS storage_path text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'email_attachments'
      AND column_name = 'attachment_id'
  ) THEN
    UPDATE public.email_attachments
    SET graph_attachment_id = attachment_id
    WHERE graph_attachment_id IS NULL
      AND attachment_id IS NOT NULL;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS email_attachments_email_graph_id_uidx
  ON public.email_attachments (email_id, graph_attachment_id)
  WHERE email_id IS NOT NULL AND graph_attachment_id IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'email_attachments_email_graph_uid'
      AND conrelid = 'public.email_attachments'::regclass
  ) THEN
    ALTER TABLE public.email_attachments
      ADD CONSTRAINT email_attachments_email_graph_uid
      UNIQUE (email_id, graph_attachment_id);
  END IF;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN unique_violation THEN NULL;
  WHEN others THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS email_attachments_message_id_idx
  ON public.email_attachments (message_id)
  WHERE message_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS email_attachments_graph_id_idx
  ON public.email_attachments (graph_attachment_id)
  WHERE graph_attachment_id IS NOT NULL;

COMMENT ON TABLE public.email_attachments IS
  'Graph email files copied to Supabase Storage. metadata only; bytes live in the email-attachments bucket.';

ALTER TABLE public.email_attachments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS email_attachments_service_all ON public.email_attachments;
CREATE POLICY email_attachments_service_all
  ON public.email_attachments
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS email_attachments_staff_read ON public.email_attachments;
CREATE POLICY email_attachments_staff_read
  ON public.email_attachments
  FOR SELECT
  TO authenticated
  USING (true);

GRANT SELECT ON public.email_attachments TO authenticated;
GRANT ALL ON public.email_attachments TO service_role;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'S'
      AND n.nspname = 'public'
      AND c.relname = 'email_attachments_id_seq'
  ) THEN
    GRANT USAGE, SELECT ON SEQUENCE public.email_attachments_id_seq TO service_role;
  END IF;
END $$;

INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES (
  'email-attachments',
  'email-attachments',
  false,
  26214400
)
ON CONFLICT (id) DO UPDATE SET
  public = excluded.public,
  file_size_limit = excluded.file_size_limit;

DROP POLICY IF EXISTS "email-attachments public read" ON storage.objects;
DROP POLICY IF EXISTS "email-attachments select policy" ON storage.objects;
CREATE POLICY "email-attachments select policy" ON storage.objects
FOR SELECT
TO authenticated
USING (bucket_id = 'email-attachments');

