-- Multi-entry subcontractor fees per lead (firm + amount + currency).
-- Replaces the single-entry leads / leads_lead.subcontractor_fee model for new writes;
-- scalar columns remain as a denormalized sum for legacy badge/report consumers.

CREATE TABLE IF NOT EXISTS public.lead_subcontractor_fees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  lead_type text CHECK (lead_type IS NULL OR lead_type IN ('new', 'legacy')),
  new_lead_id uuid REFERENCES public.leads (id) ON DELETE CASCADE,
  legacy_lead_id bigint REFERENCES public.leads_lead (id) ON DELETE CASCADE,
  lead_number text,

  firm_id uuid NOT NULL REFERENCES public.firms (id) ON DELETE RESTRICT,
  amount numeric(14, 2) NOT NULL CHECK (amount >= 0),
  currency_id integer REFERENCES public.accounting_currencies (id) ON DELETE SET NULL,
  notes text,

  created_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,

  CONSTRAINT lead_subcontractor_fees_lead_identity CHECK (
    new_lead_id IS NOT NULL OR legacy_lead_id IS NOT NULL
  ),
  CONSTRAINT lead_subcontractor_fees_one_lead CHECK (
    NOT (new_lead_id IS NOT NULL AND legacy_lead_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_lead_subcontractor_fees_new
  ON public.lead_subcontractor_fees (new_lead_id)
  WHERE new_lead_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_subcontractor_fees_legacy
  ON public.lead_subcontractor_fees (legacy_lead_id)
  WHERE legacy_lead_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_subcontractor_fees_firm
  ON public.lead_subcontractor_fees (firm_id);

CREATE INDEX IF NOT EXISTS idx_lead_subcontractor_fees_lead_number
  ON public.lead_subcontractor_fees (lead_number)
  WHERE lead_number IS NOT NULL;

COMMENT ON TABLE public.lead_subcontractor_fees IS
  'Per-lead subcontractor fee line items. Multiple rows per lead and per firm are allowed.';

COMMENT ON COLUMN public.lead_subcontractor_fees.firm_id IS
  'External firm (public.firms) charged for this fee line.';

COMMENT ON COLUMN public.lead_subcontractor_fees.amount IS
  'Fee amount in the selected accounting currency.';

ALTER TABLE public.lead_subcontractor_fees ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can view lead subcontractor fees"
  ON public.lead_subcontractor_fees;
CREATE POLICY "Authenticated can view lead subcontractor fees"
ON public.lead_subcontractor_fees FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated can insert lead subcontractor fees"
  ON public.lead_subcontractor_fees;
CREATE POLICY "Authenticated can insert lead subcontractor fees"
ON public.lead_subcontractor_fees FOR INSERT
TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated can update lead subcontractor fees"
  ON public.lead_subcontractor_fees;
CREATE POLICY "Authenticated can update lead subcontractor fees"
ON public.lead_subcontractor_fees FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated can delete lead subcontractor fees"
  ON public.lead_subcontractor_fees;
CREATE POLICY "Authenticated can delete lead subcontractor fees"
ON public.lead_subcontractor_fees FOR DELETE
TO authenticated
USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.lead_subcontractor_fees TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.lead_subcontractor_fees_id_seq TO authenticated;
