-- Multi-entry case expenses per lead (Finances → Expenses).
-- Requires: sql/2026-07-28_lead_expense_types.sql
-- Also run: sql/2026-07-28_lead_expenses_finance_link.sql if upgrading an older table.

CREATE TABLE IF NOT EXISTS public.lead_expenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  lead_type text CHECK (lead_type IS NULL OR lead_type IN ('new', 'legacy')),
  new_lead_id uuid REFERENCES public.leads (id) ON DELETE CASCADE,
  legacy_lead_id bigint REFERENCES public.leads_lead (id) ON DELETE CASCADE,
  lead_number text,

  expense_type_id uuid NOT NULL REFERENCES public.lead_expense_types (id) ON DELETE RESTRICT,
  amount numeric(14, 2) NOT NULL CHECK (amount >= 0),
  currency_id integer REFERENCES public.accounting_currencies (id) ON DELETE SET NULL,
  expense_date date,
  notes text,
  include_vat boolean NOT NULL DEFAULT false,

  -- Who paid: firm vs client (default client)
  paid_by text NOT NULL DEFAULT 'client'
    CHECK (paid_by IN ('firm', 'client')),

  is_reimbursable boolean NOT NULL DEFAULT false,
  is_reimbursed boolean NOT NULL DEFAULT false,

  -- Related client (CRM contact) — Finances expense row is created under this contact
  contact_id bigint REFERENCES public.leads_contact (id) ON DELETE SET NULL,

  -- Linked Finances "Expense" payment row (order 99)
  payment_plan_id bigint,
  legacy_payment_plan_row_id bigint,

  created_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users (id) ON DELETE SET NULL,

  CONSTRAINT lead_expenses_lead_identity CHECK (
    new_lead_id IS NOT NULL OR legacy_lead_id IS NOT NULL
  ),
  CONSTRAINT lead_expenses_one_lead CHECK (
    NOT (new_lead_id IS NOT NULL AND legacy_lead_id IS NOT NULL)
  ),
  CONSTRAINT lead_expenses_reimbursed_implies_reimbursable CHECK (
    NOT is_reimbursed OR is_reimbursable
  )
);

CREATE INDEX IF NOT EXISTS idx_lead_expenses_new
  ON public.lead_expenses (new_lead_id)
  WHERE new_lead_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_expenses_legacy
  ON public.lead_expenses (legacy_lead_id)
  WHERE legacy_lead_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_expenses_type
  ON public.lead_expenses (expense_type_id);

CREATE INDEX IF NOT EXISTS idx_lead_expenses_contact
  ON public.lead_expenses (contact_id)
  WHERE contact_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_expenses_lead_number
  ON public.lead_expenses (lead_number)
  WHERE lead_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_expenses_paid_by
  ON public.lead_expenses (paid_by);

CREATE INDEX IF NOT EXISTS idx_lead_expenses_payment_plan
  ON public.lead_expenses (payment_plan_id)
  WHERE payment_plan_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_expenses_legacy_payment_plan
  ON public.lead_expenses (legacy_payment_plan_row_id)
  WHERE legacy_payment_plan_row_id IS NOT NULL;

COMMENT ON TABLE public.lead_expenses IS
  'Per-lead case expense line items. Creates a matching Expense Finances payment row.';

COMMENT ON COLUMN public.lead_expenses.paid_by IS
  'firm = Paid by the firm; client = Paid directly by the client. Default: client.';

COMMENT ON COLUMN public.lead_expenses.include_vat IS
  'When true, linked Finances expense row stores VAT. Default false (without VAT).';

COMMENT ON COLUMN public.lead_expenses.is_reimbursable IS
  'Expense is expected to be reimbursed by the client.';

COMMENT ON COLUMN public.lead_expenses.is_reimbursed IS
  'Expense has already been reimbursed. Requires is_reimbursable = true.';

COMMENT ON COLUMN public.lead_expenses.contact_id IS
  'Related client contact (public.leads_contact); Finances row is filed under this contact.';

COMMENT ON COLUMN public.lead_expenses.payment_plan_id IS
  'Linked payment_plans.id (new leads).';

COMMENT ON COLUMN public.lead_expenses.legacy_payment_plan_row_id IS
  'Linked finances_paymentplanrow.id (legacy leads).';

ALTER TABLE public.lead_expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can view lead expenses"
  ON public.lead_expenses;
CREATE POLICY "Authenticated can view lead expenses"
ON public.lead_expenses FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated can insert lead expenses"
  ON public.lead_expenses;
CREATE POLICY "Authenticated can insert lead expenses"
ON public.lead_expenses FOR INSERT
TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated can update lead expenses"
  ON public.lead_expenses;
CREATE POLICY "Authenticated can update lead expenses"
ON public.lead_expenses FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated can delete lead expenses"
  ON public.lead_expenses;
CREATE POLICY "Authenticated can delete lead expenses"
ON public.lead_expenses FOR DELETE
TO authenticated
USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.lead_expenses TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.lead_expenses_id_seq TO authenticated;

ALTER TABLE public.lead_expenses ALTER COLUMN paid_by SET DEFAULT 'client';
