-- Absolute max employee-cost overrides for a lead (management can set freely from Leads management detail).
-- When present, this replaces the formula max (14% of 87% of lead value + approved extensions).

CREATE TABLE IF NOT EXISTS public.lead_employee_cost_max_overrides (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  lead_type text CHECK (lead_type IS NULL OR lead_type IN ('new', 'legacy')),
  new_lead_id uuid,
  legacy_lead_id bigint,
  lead_number text,

  max_allowed_cost_nis numeric(12, 2) NOT NULL CHECK (max_allowed_cost_nis >= 0),

  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by_employee_id bigint REFERENCES public.tenants_employee(id) ON DELETE SET NULL,

  CONSTRAINT lead_employee_cost_max_overrides_lead_identity CHECK (
    new_lead_id IS NOT NULL OR legacy_lead_id IS NOT NULL OR (lead_number IS NOT NULL AND length(btrim(lead_number)) > 0)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_lead_cost_max_override_new
  ON public.lead_employee_cost_max_overrides (new_lead_id)
  WHERE new_lead_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_lead_cost_max_override_legacy
  ON public.lead_employee_cost_max_overrides (legacy_lead_id)
  WHERE legacy_lead_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_lead_cost_max_override_lead_number
  ON public.lead_employee_cost_max_overrides (lead_number)
  WHERE new_lead_id IS NULL AND legacy_lead_id IS NULL AND lead_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_cost_max_override_new
  ON public.lead_employee_cost_max_overrides (new_lead_id)
  WHERE new_lead_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_lead_cost_max_override_legacy
  ON public.lead_employee_cost_max_overrides (legacy_lead_id)
  WHERE legacy_lead_id IS NOT NULL;

COMMENT ON TABLE public.lead_employee_cost_max_overrides IS
  'Management override for a lead employee-cost max; when set, replaces formula + extension max.';

ALTER TABLE public.lead_employee_cost_max_overrides ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Superusers can view lead cost max overrides"
  ON public.lead_employee_cost_max_overrides;
CREATE POLICY "Superusers can view lead cost max overrides"
ON public.lead_employee_cost_max_overrides FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
      )
  )
);

-- Authenticated users can read overrides so cost gates work for all roles
DROP POLICY IF EXISTS "Authenticated can view lead cost max overrides"
  ON public.lead_employee_cost_max_overrides;
CREATE POLICY "Authenticated can view lead cost max overrides"
ON public.lead_employee_cost_max_overrides FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Superusers can insert lead cost max overrides"
  ON public.lead_employee_cost_max_overrides;
CREATE POLICY "Superusers can insert lead cost max overrides"
ON public.lead_employee_cost_max_overrides FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
      )
  )
);

DROP POLICY IF EXISTS "Superusers can update lead cost max overrides"
  ON public.lead_employee_cost_max_overrides;
CREATE POLICY "Superusers can update lead cost max overrides"
ON public.lead_employee_cost_max_overrides FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
      )
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
      )
  )
);

DROP POLICY IF EXISTS "Superusers can delete lead cost max overrides"
  ON public.lead_employee_cost_max_overrides;
CREATE POLICY "Superusers can delete lead cost max overrides"
ON public.lead_employee_cost_max_overrides FOR DELETE
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.auth_id = auth.uid()
      AND (
        u.is_superuser IS TRUE
        OR u.is_superuser::text IN ('true', 't', '1')
      )
  )
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.lead_employee_cost_max_overrides TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.lead_employee_cost_max_overrides_id_seq TO authenticated;
