-- Sub efforts (stage 110 dropdown options)
-- Stores selectable effort templates/options.

create table if not exists public.sub_efforts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now(),
  created_by text null,
  updated_by text null,
  updated_at timestamptz not null default now()
);

-- RLS + permissions
alter table public.sub_efforts enable row level security;
drop policy if exists "sub_efforts_authenticated_select" on public.sub_efforts;
create policy "sub_efforts_authenticated_select" on public.sub_efforts
  for select
  to authenticated
  using (true);

-- Keep updated_at current
create or replace function public.sub_efforts_set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists sub_efforts_set_updated_at on public.sub_efforts;
create trigger sub_efforts_set_updated_at
before update on public.sub_efforts
for each row
execute function public.sub_efforts_set_updated_at();

-- Per-lead/per-employee sub-effort rows (details)
create table if not exists public.lead_sub_efforts (
  id bigint generated by default as identity primary key,
  sub_effort_id bigint not null references public.sub_efforts(id) on delete restrict,
  legacy_lead_id bigint null,
  new_lead_id uuid null references public.leads(id) on delete cascade,
  employee_id bigint null references public.tenants_employee(id),
  created_at timestamptz not null default now(),
  created_by text null,
  updated_by text null,
  updated_at timestamptz not null default now(),
  internal boolean not null default false,
  active boolean not null default true,
  document_url jsonb null,
  internal_notes text null,
  client_notes text null
);

alter table public.lead_sub_efforts enable row level security;
drop policy if exists "lead_sub_efforts_authenticated_select" on public.lead_sub_efforts;
drop policy if exists "lead_sub_efforts_authenticated_insert" on public.lead_sub_efforts;
drop policy if exists "lead_sub_efforts_authenticated_update" on public.lead_sub_efforts;
drop policy if exists "lead_sub_efforts_authenticated_delete" on public.lead_sub_efforts;

create policy "lead_sub_efforts_authenticated_select" on public.lead_sub_efforts
  for select
  to authenticated
  using (true);

create policy "lead_sub_efforts_authenticated_insert" on public.lead_sub_efforts
  for insert
  to authenticated
  with check (true);

create policy "lead_sub_efforts_authenticated_update" on public.lead_sub_efforts
  for update
  to authenticated
  using (true)
  with check (true);

create policy "lead_sub_efforts_authenticated_delete" on public.lead_sub_efforts
  for delete
  to authenticated
  using (true);

create index if not exists idx_lead_sub_efforts_sub_effort_id on public.lead_sub_efforts(sub_effort_id);
create index if not exists idx_lead_sub_efforts_legacy_lead_id on public.lead_sub_efforts(legacy_lead_id);
create index if not exists idx_lead_sub_efforts_new_lead_id on public.lead_sub_efforts(new_lead_id);
create index if not exists idx_lead_sub_efforts_employee_id on public.lead_sub_efforts(employee_id);

create or replace function public.lead_sub_efforts_set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists lead_sub_efforts_set_updated_at on public.lead_sub_efforts;
create trigger lead_sub_efforts_set_updated_at
before update on public.lead_sub_efforts
for each row
execute function public.lead_sub_efforts_set_updated_at();

-- Grants (required for client-side inserts under RLS)
grant usage on schema public to authenticated;
grant select on public.sub_efforts to authenticated;
grant select, insert, update, delete on public.lead_sub_efforts to authenticated;
do $$
begin
  -- Identity/sequence access for inserts
  grant usage, select on sequence public.sub_efforts_id_seq to authenticated;
exception when undefined_table or invalid_schema_name then
  null;
end;
$$;
do $$
begin
  grant usage, select on sequence public.lead_sub_efforts_id_seq to authenticated;
exception when undefined_table or invalid_schema_name then
  null;
end;
$$;

-- Seed initial options (idempotent)
insert into public.sub_efforts (name)
values
  ('Aplication submitted'),
  ('Communication with client')
on conflict (name) do update
set name = excluded.name;

