-- Sub-category efforts: breakdown rows under each sub_effort template.
-- Run in Supabase SQL editor.

CREATE TABLE IF NOT EXISTS public.sub_category_efforts (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sub_effort_id bigint NOT NULL,
  name text NOT NULL,
  description text NULL,
  sort_order integer NOT NULL DEFAULT 0,
  percentage numeric(5, 2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NULL,
  updated_by text NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sub_category_efforts_pkey PRIMARY KEY (id),
  CONSTRAINT sub_category_efforts_sub_effort_id_fkey
    FOREIGN KEY (sub_effort_id) REFERENCES public.sub_efforts (id) ON DELETE CASCADE,
  CONSTRAINT sub_category_efforts_percentage_range_chk
    CHECK (percentage >= 0 AND percentage <= 100)
);

COMMENT ON TABLE public.sub_category_efforts IS
  'Ordered sub-categories belonging to a sub_effort template (description, display order, weight %).';

COMMENT ON COLUMN public.sub_category_efforts.sub_effort_id IS
  'Parent sub effort from public.sub_efforts.';

COMMENT ON COLUMN public.sub_category_efforts.name IS
  'Short display name for this sub-category effort step.';

COMMENT ON COLUMN public.sub_category_efforts.description IS
  'Longer explanatory text for this sub-category effort step.';

COMMENT ON COLUMN public.sub_category_efforts.sort_order IS
  'Display order within the parent sub_effort (0 = first).';

COMMENT ON COLUMN public.sub_category_efforts.percentage IS
  'Weight share for this sub-category (0–100).';

CREATE INDEX IF NOT EXISTS idx_sub_category_efforts_sub_effort_id
  ON public.sub_category_efforts USING btree (sub_effort_id);

CREATE INDEX IF NOT EXISTS idx_sub_category_efforts_sub_effort_sort_order
  ON public.sub_category_efforts USING btree (sub_effort_id, sort_order);

CREATE OR REPLACE FUNCTION public.sub_category_efforts_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sub_category_efforts_set_updated_at ON public.sub_category_efforts;

CREATE TRIGGER sub_category_efforts_set_updated_at
BEFORE UPDATE ON public.sub_category_efforts
FOR EACH ROW
EXECUTE FUNCTION public.sub_category_efforts_set_updated_at();

ALTER TABLE public.sub_category_efforts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sub_category_efforts_authenticated_select" ON public.sub_category_efforts;
DROP POLICY IF EXISTS "sub_category_efforts_authenticated_insert" ON public.sub_category_efforts;
DROP POLICY IF EXISTS "sub_category_efforts_authenticated_update" ON public.sub_category_efforts;
DROP POLICY IF EXISTS "sub_category_efforts_authenticated_delete" ON public.sub_category_efforts;

CREATE POLICY "sub_category_efforts_authenticated_select" ON public.sub_category_efforts
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "sub_category_efforts_authenticated_insert" ON public.sub_category_efforts
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "sub_category_efforts_authenticated_update" ON public.sub_category_efforts
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "sub_category_efforts_authenticated_delete" ON public.sub_category_efforts
  FOR DELETE
  TO authenticated
  USING (true);

GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sub_category_efforts TO authenticated;

DO $$
BEGIN
  GRANT USAGE, SELECT ON SEQUENCE public.sub_category_efforts_id_seq TO authenticated;
EXCEPTION
  WHEN undefined_table OR invalid_schema_name THEN
    NULL;
END;
$$;
