-- Employee lead daily activity + time allocation reporting.
-- Run after tenants_employee, users, leads, and leads_lead exist.

-- ---------------------------------------------------------------------------
-- 1. Daily lead views (cross-browser activity capture)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.employee_lead_daily_activity (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id bigint NOT NULL,
    user_id uuid NOT NULL,
    activity_date date NOT NULL,
    lead_type text NOT NULL CHECK (lead_type IN ('new', 'legacy')),
    new_lead_id uuid,
    legacy_lead_id bigint,
    lead_number text NOT NULL,
    client_name text NOT NULL DEFAULT '',
    view_count integer NOT NULL DEFAULT 1 CHECK (view_count >= 1),
    first_viewed_at timestamptz NOT NULL DEFAULT now(),
    last_viewed_at timestamptz NOT NULL DEFAULT now(),
    lead_identity_key text GENERATED ALWAYS AS (
        CASE
            WHEN lead_type = 'new' THEN 'n:' || new_lead_id::text
            ELSE 'l:' || legacy_lead_id::text
        END
    ) STORED,
    CONSTRAINT employee_lead_daily_activity_pkey PRIMARY KEY (id),
    CONSTRAINT employee_lead_daily_activity_employee_id_fkey
        FOREIGN KEY (employee_id) REFERENCES public.tenants_employee(id) ON DELETE CASCADE,
    CONSTRAINT employee_lead_daily_activity_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT employee_lead_daily_activity_new_lead_id_fkey
        FOREIGN KEY (new_lead_id) REFERENCES public.leads(id) ON DELETE CASCADE,
    CONSTRAINT employee_lead_daily_activity_legacy_lead_id_fkey
        FOREIGN KEY (legacy_lead_id) REFERENCES public.leads_lead(id) ON DELETE CASCADE,
    CONSTRAINT employee_lead_daily_activity_lead_chk CHECK (
        (lead_type = 'new' AND new_lead_id IS NOT NULL AND legacy_lead_id IS NULL)
        OR (lead_type = 'legacy' AND legacy_lead_id IS NOT NULL AND new_lead_id IS NULL)
    ),
    CONSTRAINT employee_lead_daily_activity_employee_day_lead_key
        UNIQUE (employee_id, activity_date, lead_identity_key)
);

CREATE INDEX IF NOT EXISTS idx_employee_lead_daily_activity_employee_date
    ON public.employee_lead_daily_activity(employee_id, activity_date DESC);

CREATE INDEX IF NOT EXISTS idx_employee_lead_daily_activity_date
    ON public.employee_lead_daily_activity(activity_date DESC);

COMMENT ON TABLE public.employee_lead_daily_activity IS
    'Leads an employee opened on a given calendar day (Jerusalem date from app).';

-- ---------------------------------------------------------------------------
-- 2. Daily allocation header (one row per employee per work day)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.employee_daily_lead_allocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id bigint NOT NULL,
    user_id uuid NOT NULL,
    work_date date NOT NULL,
    submitted_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    notes text,
    other_work_percent numeric(5, 2) NOT NULL DEFAULT 0
        CHECK (other_work_percent >= 0 AND other_work_percent <= 100),
    CONSTRAINT employee_daily_lead_allocations_pkey PRIMARY KEY (id),
    CONSTRAINT employee_daily_lead_allocations_employee_id_fkey
        FOREIGN KEY (employee_id) REFERENCES public.tenants_employee(id) ON DELETE CASCADE,
    CONSTRAINT employee_daily_lead_allocations_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT employee_daily_lead_allocations_employee_work_date_key
        UNIQUE (employee_id, work_date)
);

CREATE INDEX IF NOT EXISTS idx_employee_daily_lead_allocations_work_date
    ON public.employee_daily_lead_allocations(work_date DESC);

COMMENT ON TABLE public.employee_daily_lead_allocations IS
    'Employee daily lead time allocation submission (percentages sum to 100 on items).';

-- ---------------------------------------------------------------------------
-- 3. Allocation line items
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.employee_daily_lead_allocation_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    allocation_id bigint NOT NULL,
    lead_type text NOT NULL CHECK (lead_type IN ('new', 'legacy')),
    new_lead_id uuid,
    legacy_lead_id bigint,
    lead_number text NOT NULL,
    client_name text NOT NULL DEFAULT '',
    percent numeric(5, 2) NOT NULL CHECK (percent > 0 AND percent <= 100),
    lead_identity_key text GENERATED ALWAYS AS (
        CASE
            WHEN lead_type = 'new' THEN 'n:' || new_lead_id::text
            ELSE 'l:' || legacy_lead_id::text
        END
    ) STORED,
    CONSTRAINT employee_daily_lead_allocation_items_pkey PRIMARY KEY (id),
    CONSTRAINT employee_daily_lead_allocation_items_allocation_id_fkey
        FOREIGN KEY (allocation_id) REFERENCES public.employee_daily_lead_allocations(id) ON DELETE CASCADE,
    CONSTRAINT employee_daily_lead_allocation_items_lead_chk CHECK (
        (lead_type = 'new' AND new_lead_id IS NOT NULL AND legacy_lead_id IS NULL)
        OR (lead_type = 'legacy' AND legacy_lead_id IS NOT NULL AND new_lead_id IS NULL)
    ),
    CONSTRAINT employee_daily_lead_allocation_items_allocation_lead_key
        UNIQUE (allocation_id, lead_identity_key)
);

CREATE INDEX IF NOT EXISTS idx_employee_daily_lead_allocation_items_allocation
    ON public.employee_daily_lead_allocation_items(allocation_id);

-- ---------------------------------------------------------------------------
-- RLS helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.is_app_superuser()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.auth_id = auth.uid()
          AND (
              u.is_superuser IS TRUE
              OR u.is_superuser::text IN ('true', 't', '1')
          )
    );
$$;

CREATE OR REPLACE FUNCTION public.current_user_employee_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT u.employee_id
    FROM public.users u
    WHERE u.auth_id = auth.uid()
    LIMIT 1;
$$;

-- ---------------------------------------------------------------------------
-- Upsert activity RPC
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.upsert_employee_lead_daily_activity(
    p_activity_date date,
    p_lead_type text,
    p_new_lead_id uuid,
    p_legacy_lead_id bigint,
    p_lead_number text,
    p_client_name text DEFAULT ''
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_employee_id bigint;
    v_user_id uuid;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    v_employee_id := current_user_employee_id();
    IF v_employee_id IS NULL THEN
        RETURN;
    END IF;

    IF p_lead_type NOT IN ('new', 'legacy') THEN
        RAISE EXCEPTION 'Invalid lead_type';
    END IF;

    IF p_lead_type = 'new' AND p_new_lead_id IS NULL THEN
        RAISE EXCEPTION 'new_lead_id required';
    END IF;

    IF p_lead_type = 'legacy' AND p_legacy_lead_id IS NULL THEN
        RAISE EXCEPTION 'legacy_lead_id required';
    END IF;

    INSERT INTO public.employee_lead_daily_activity (
        employee_id,
        user_id,
        activity_date,
        lead_type,
        new_lead_id,
        legacy_lead_id,
        lead_number,
        client_name,
        view_count,
        first_viewed_at,
        last_viewed_at
    )
    VALUES (
        v_employee_id,
        v_user_id,
        p_activity_date,
        p_lead_type,
        p_new_lead_id,
        p_legacy_lead_id,
        COALESCE(NULLIF(trim(p_lead_number), ''), '?'),
        COALESCE(NULLIF(trim(p_client_name), ''), 'Unknown'),
        1,
        now(),
        now()
    )
    ON CONFLICT (employee_id, activity_date, lead_identity_key)
    DO UPDATE SET
        view_count = employee_lead_daily_activity.view_count + 1,
        last_viewed_at = now(),
        lead_number = EXCLUDED.lead_number,
        client_name = EXCLUDED.client_name;
END;
$$;

GRANT EXECUTE ON FUNCTION public.upsert_employee_lead_daily_activity(
    date, text, uuid, bigint, text, text
) TO authenticated;

-- ---------------------------------------------------------------------------
-- RLS: activity
-- ---------------------------------------------------------------------------

ALTER TABLE public.employee_lead_daily_activity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Employees view own lead daily activity"
    ON public.employee_lead_daily_activity;
CREATE POLICY "Employees view own lead daily activity"
    ON public.employee_lead_daily_activity FOR SELECT
    TO authenticated
    USING (employee_id = current_user_employee_id());

DROP POLICY IF EXISTS "Superusers view all lead daily activity"
    ON public.employee_lead_daily_activity;
CREATE POLICY "Superusers view all lead daily activity"
    ON public.employee_lead_daily_activity FOR SELECT
    TO authenticated
    USING (is_app_superuser());

-- ---------------------------------------------------------------------------
-- RLS: allocations
-- ---------------------------------------------------------------------------

ALTER TABLE public.employee_daily_lead_allocations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Employees manage own lead allocations"
    ON public.employee_daily_lead_allocations;
CREATE POLICY "Employees manage own lead allocations"
    ON public.employee_daily_lead_allocations FOR ALL
    TO authenticated
    USING (employee_id = current_user_employee_id())
    WITH CHECK (
        employee_id = current_user_employee_id()
        AND user_id = auth.uid()
    );

DROP POLICY IF EXISTS "Superusers view all lead allocations"
    ON public.employee_daily_lead_allocations;
CREATE POLICY "Superusers view all lead allocations"
    ON public.employee_daily_lead_allocations FOR SELECT
    TO authenticated
    USING (is_app_superuser());

-- ---------------------------------------------------------------------------
-- RLS: allocation items (via parent ownership)
-- ---------------------------------------------------------------------------

ALTER TABLE public.employee_daily_lead_allocation_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Employees manage own allocation items"
    ON public.employee_daily_lead_allocation_items;
CREATE POLICY "Employees manage own allocation items"
    ON public.employee_daily_lead_allocation_items FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1
            FROM public.employee_daily_lead_allocations a
            WHERE a.id = allocation_id
              AND a.employee_id = current_user_employee_id()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1
            FROM public.employee_daily_lead_allocations a
            WHERE a.id = allocation_id
              AND a.employee_id = current_user_employee_id()
        )
    );

DROP POLICY IF EXISTS "Superusers view all allocation items"
    ON public.employee_daily_lead_allocation_items;
CREATE POLICY "Superusers view all allocation items"
    ON public.employee_daily_lead_allocation_items FOR SELECT
    TO authenticated
    USING (is_app_superuser());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.employee_lead_daily_activity TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.employee_daily_lead_allocations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.employee_daily_lead_allocation_items TO authenticated;
