-- Client portal: password-protected public case view for lead contacts.
-- Run after pgcrypto is enabled (see sql/auth_user_management.sql).

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE OR REPLACE FUNCTION public.portal_hash_password(p_plain TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  BEGIN
    RETURN extensions.crypt(p_plain, extensions.gen_salt('bf'::text));
  EXCEPTION
    WHEN undefined_function OR invalid_schema_name THEN
      RETURN crypt(p_plain, gen_salt('bf'::text));
  END;
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_check_password(p_plain TEXT, p_hash TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  BEGIN
    RETURN extensions.crypt(p_plain, p_hash) = p_hash;
  EXCEPTION
    WHEN undefined_function OR invalid_schema_name THEN
      RETURN crypt(p_plain, p_hash) = p_hash;
  END;
END;
$$;

GRANT EXECUTE ON FUNCTION public.portal_hash_password(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.portal_check_password(TEXT, TEXT) TO authenticated, anon;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.client_portal_access (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  new_lead_id UUID NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  legacy_lead_id BIGINT NULL REFERENCES public.leads_lead(id) ON DELETE CASCADE,
  password_hash TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by TEXT NULL,
  CONSTRAINT client_portal_access_one_lead CHECK (
    (new_lead_id IS NOT NULL AND legacy_lead_id IS NULL)
    OR (new_lead_id IS NULL AND legacy_lead_id IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS client_portal_access_new_lead_id_unique
  ON public.client_portal_access (new_lead_id)
  WHERE new_lead_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS client_portal_access_legacy_lead_id_unique
  ON public.client_portal_access (legacy_lead_id)
  WHERE legacy_lead_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.client_portal_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_token UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  contact_id BIGINT NOT NULL REFERENCES public.leads_contact(id) ON DELETE CASCADE,
  new_lead_id UUID NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  legacy_lead_id BIGINT NULL REFERENCES public.leads_lead(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT client_portal_sessions_one_lead CHECK (
    (new_lead_id IS NOT NULL AND legacy_lead_id IS NULL)
    OR (new_lead_id IS NULL AND legacy_lead_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_client_portal_sessions_token
  ON public.client_portal_sessions (session_token);

CREATE INDEX IF NOT EXISTS idx_client_portal_sessions_expires
  ON public.client_portal_sessions (expires_at);

CREATE TABLE IF NOT EXISTS public.client_portal_meeting_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id BIGINT NOT NULL REFERENCES public.leads_contact(id) ON DELETE CASCADE,
  new_lead_id UUID NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  legacy_lead_id BIGINT NULL REFERENCES public.leads_lead(id) ON DELETE CASCADE,
  preferred_date DATE NOT NULL,
  preferred_time_range TEXT NULL,
  notes TEXT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT client_portal_meeting_requests_one_lead CHECK (
    (new_lead_id IS NOT NULL AND legacy_lead_id IS NULL)
    OR (new_lead_id IS NULL AND legacy_lead_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_client_portal_meeting_requests_lead_pending
  ON public.client_portal_meeting_requests (new_lead_id, legacy_lead_id, status)
  WHERE status = 'pending';

-- Short-lived upload grants for portal document uploads (anon storage policy).
CREATE TABLE IF NOT EXISTS public.client_portal_upload_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES public.client_portal_sessions(id) ON DELETE CASCADE,
  storage_path TEXT NOT NULL UNIQUE,
  file_name TEXT NOT NULL,
  mime_type TEXT NULL,
  file_size BIGINT NULL,
  used BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS: portal tables are accessed via SECURITY DEFINER RPCs only (anon).
ALTER TABLE public.client_portal_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_portal_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_portal_meeting_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_portal_upload_tokens ENABLE ROW LEVEL SECURITY;

-- Staff can read meeting requests and manage portal access.
DROP POLICY IF EXISTS client_portal_meeting_requests_staff_select ON public.client_portal_meeting_requests;
CREATE POLICY client_portal_meeting_requests_staff_select
  ON public.client_portal_meeting_requests
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS client_portal_meeting_requests_staff_update ON public.client_portal_meeting_requests;
CREATE POLICY client_portal_meeting_requests_staff_update
  ON public.client_portal_meeting_requests
  FOR UPDATE TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS client_portal_access_staff_all ON public.client_portal_access;
CREATE POLICY client_portal_access_staff_all
  ON public.client_portal_access
  FOR ALL TO authenticated
  USING (true)
  WITH CHECK (true);

-- ---------------------------------------------------------------------------
-- Internal helpers
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public._portal_resolve_lead_ref(p_lead_ref TEXT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ref TEXT := NULLIF(TRIM(p_lead_ref), '');
  v_legacy RECORD;
  v_new RECORD;
  v_stage_name TEXT;
BEGIN
  IF v_ref IS NULL THEN
    RETURN NULL;
  END IF;

  -- New lead by UUID
  IF v_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
    SELECT l.id, l.name, l.lead_number, l.manual_id, l.stage::TEXT
    INTO v_new
    FROM public.leads l
    WHERE l.id = v_ref::UUID
    LIMIT 1;

    IF FOUND THEN
      SELECT ls.name INTO v_stage_name
      FROM public.lead_stages ls
      WHERE ls.id::TEXT = v_new.stage OR ls.name = v_new.stage
      LIMIT 1;

      RETURN jsonb_build_object(
        'is_legacy', false,
        'new_lead_id', v_new.id,
        'legacy_lead_id', NULL,
        'lead_number', COALESCE(NULLIF(TRIM(v_new.lead_number::TEXT), ''), NULLIF(TRIM(v_new.manual_id::TEXT), ''), v_new.id::TEXT),
        'display_name', v_new.name,
        'stage', v_new.stage,
        'stage_name', COALESCE(v_stage_name, v_new.stage)
      );
    END IF;
  END IF;

  -- Legacy by numeric id
  IF v_ref ~ '^\d+$' THEN
    SELECT ll.id, ll.name, ll.lead_number, ll.manual_id, ll.stage
    INTO v_legacy
    FROM public.leads_lead ll
    WHERE ll.id = v_ref::BIGINT
    LIMIT 1;

    IF FOUND THEN
      SELECT ls.name INTO v_stage_name
      FROM public.lead_stages ls
      WHERE ls.id::TEXT = v_legacy.stage::TEXT OR ls.name = v_legacy.stage::TEXT
      LIMIT 1;

      RETURN jsonb_build_object(
        'is_legacy', true,
        'new_lead_id', NULL,
        'legacy_lead_id', v_legacy.id,
        'lead_number', COALESCE(NULLIF(TRIM(v_legacy.lead_number::TEXT), ''), NULLIF(TRIM(v_legacy.manual_id::TEXT), ''), v_legacy.id::TEXT),
        'display_name', v_legacy.name,
        'stage', v_legacy.stage,
        'stage_name', COALESCE(v_stage_name, v_legacy.stage::TEXT)
      );
    END IF;
  END IF;

  -- New lead by lead_number or manual_id
  SELECT l.id, l.name, l.lead_number, l.manual_id, l.stage::TEXT
  INTO v_new
  FROM public.leads l
  WHERE NULLIF(TRIM(l.lead_number::TEXT), '') = v_ref
     OR NULLIF(TRIM(l.manual_id::TEXT), '') = v_ref
  LIMIT 1;

  IF FOUND THEN
    SELECT ls.name INTO v_stage_name
    FROM public.lead_stages ls
    WHERE ls.id::TEXT = v_new.stage OR ls.name = v_new.stage
    LIMIT 1;

    RETURN jsonb_build_object(
      'is_legacy', false,
      'new_lead_id', v_new.id,
      'legacy_lead_id', NULL,
      'lead_number', COALESCE(NULLIF(TRIM(v_new.lead_number::TEXT), ''), NULLIF(TRIM(v_new.manual_id::TEXT), ''), v_new.id::TEXT),
      'display_name', v_new.name,
      'stage', v_new.stage,
      'stage_name', COALESCE(v_stage_name, v_new.stage)
    );
  END IF;

  -- Legacy by lead_number or manual_id
  SELECT ll.id, ll.name, ll.lead_number, ll.manual_id, ll.stage
  INTO v_legacy
  FROM public.leads_lead ll
  WHERE NULLIF(TRIM(ll.lead_number::TEXT), '') = v_ref
     OR NULLIF(TRIM(ll.manual_id::TEXT), '') = v_ref
  LIMIT 1;

  IF FOUND THEN
    SELECT ls.name INTO v_stage_name
    FROM public.lead_stages ls
    WHERE ls.id::TEXT = v_legacy.stage::TEXT OR ls.name = v_legacy.stage::TEXT
    LIMIT 1;

    RETURN jsonb_build_object(
      'is_legacy', true,
      'new_lead_id', NULL,
      'legacy_lead_id', v_legacy.id,
      'lead_number', COALESCE(NULLIF(TRIM(v_legacy.lead_number::TEXT), ''), NULLIF(TRIM(v_legacy.manual_id::TEXT), ''), v_legacy.id::TEXT),
      'display_name', v_legacy.name,
      'stage', v_legacy.stage,
      'stage_name', COALESCE(v_stage_name, v_legacy.stage::TEXT)
    );
  END IF;

  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public._portal_contact_on_lead(
  p_email TEXT,
  p_new_lead_id UUID,
  p_legacy_lead_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_contact_id BIGINT;
  v_email TEXT := lower(trim(p_email));
BEGIN
  IF v_email IS NULL OR v_email = '' THEN
    RETURN NULL;
  END IF;

  IF p_legacy_lead_id IS NOT NULL THEN
    SELECT lc.id INTO v_contact_id
    FROM public.leads_contact lc
    INNER JOIN public.lead_leadcontact llc ON llc.contact_id::TEXT = lc.id::TEXT
    WHERE lower(trim(coalesce(lc.email, ''))) = v_email
      AND llc.lead_id::TEXT = p_legacy_lead_id::TEXT
    LIMIT 1;
    RETURN v_contact_id;
  END IF;

  IF p_new_lead_id IS NOT NULL THEN
    SELECT lc.id INTO v_contact_id
    FROM public.leads_contact lc
    INNER JOIN public.lead_leadcontact llc ON llc.contact_id::TEXT = lc.id::TEXT
    WHERE lower(trim(coalesce(lc.email, ''))) = v_email
      AND llc.newlead_id::TEXT = p_new_lead_id::TEXT
    LIMIT 1;
    RETURN v_contact_id;
  END IF;

  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public._portal_session_row(p_token UUID)
RETURNS public.client_portal_sessions
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.client_portal_sessions;
BEGIN
  SELECT * INTO v_row
  FROM public.client_portal_sessions s
  WHERE s.session_token = p_token
    AND s.expires_at > NOW()
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public._portal_access_for_lead(
  p_new_lead_id UUID,
  p_legacy_lead_id BIGINT
)
RETURNS public.client_portal_access
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.client_portal_access;
BEGIN
  IF p_legacy_lead_id IS NOT NULL THEN
    SELECT * INTO v_row
    FROM public.client_portal_access a
    WHERE a.legacy_lead_id = p_legacy_lead_id
      AND a.enabled = TRUE
    LIMIT 1;
  ELSE
    SELECT * INTO v_row
    FROM public.client_portal_access a
    WHERE a.new_lead_id = p_new_lead_id
      AND a.enabled = TRUE
    LIMIT 1;
  END IF;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  RETURN v_row;
END;
$$;

-- Parse employee id from bigint/text columns (leads roles may be text or FK bigint).
CREATE OR REPLACE FUNCTION public._portal_parse_employee_id(p_value TEXT)
RETURNS BIGINT
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT CASE
    WHEN p_value IS NULL OR TRIM(p_value) IN ('', '---', 'Not assigned') THEN NULL
    WHEN TRIM(p_value) ~ '^[0-9]+$' THEN TRIM(p_value)::BIGINT
    ELSE NULL
  END;
$$;

CREATE OR REPLACE FUNCTION public._portal_employee_display_name(p_employee_id BIGINT)
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(NULLIF(TRIM(te.official_name), ''), NULLIF(TRIM(te.display_name), ''))
  FROM public.tenants_employee te
  WHERE te.id = p_employee_id
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public._portal_role_display(p_employee_id BIGINT, p_text_value TEXT)
RETURNS TEXT
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(
    public._portal_employee_display_name(p_employee_id),
    public._portal_employee_display_name(public._portal_parse_employee_id(p_text_value)),
    NULLIF(TRIM(p_text_value), ''),
    NULLIF(TRIM(p_text_value), '---'),
    NULLIF(TRIM(p_text_value), 'Not assigned')
  );
$$;

-- ---------------------------------------------------------------------------
-- Public RPCs (anon)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.portal_login(
  p_lead_ref TEXT,
  p_email TEXT,
  p_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_lead JSONB;
  v_access public.client_portal_access;
  v_contact_id BIGINT;
  v_session public.client_portal_sessions;
  v_new_lead_id UUID;
  v_legacy_lead_id BIGINT;
  v_contact JSONB;
BEGIN
  v_lead := public._portal_resolve_lead_ref(p_lead_ref);
  IF v_lead IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Invalid email or password');
  END IF;

  v_new_lead_id := (v_lead->>'new_lead_id')::UUID;
  v_legacy_lead_id := (v_lead->>'legacy_lead_id')::BIGINT;

  v_access := public._portal_access_for_lead(v_new_lead_id, v_legacy_lead_id);
  IF v_access IS NULL OR v_access.password_hash IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Invalid email or password');
  END IF;

  IF NOT public.portal_check_password(p_password, v_access.password_hash) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Invalid email or password');
  END IF;

  v_contact_id := public._portal_contact_on_lead(p_email, v_new_lead_id, v_legacy_lead_id);
  IF v_contact_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Invalid email or password');
  END IF;

  INSERT INTO public.client_portal_sessions (
    contact_id, new_lead_id, legacy_lead_id, expires_at
  ) VALUES (
    v_contact_id,
    v_new_lead_id,
    v_legacy_lead_id,
    NOW() + INTERVAL '7 days'
  )
  RETURNING * INTO v_session;

  SELECT jsonb_build_object(
    'id', lc.id,
    'name', lc.name,
    'email', lc.email
  ) INTO v_contact
  FROM public.leads_contact lc
  WHERE lc.id = v_contact_id;

  RETURN jsonb_build_object(
    'ok', true,
    'session_token', v_session.session_token,
    'lead_ref', COALESCE(v_lead->>'lead_number', p_lead_ref),
    'lead_summary', v_lead,
    'contact', v_contact
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_validate_session(p_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.client_portal_sessions;
  v_lead JSONB;
  v_contact JSONB;
BEGIN
  v_session := public._portal_session_row(p_token);
  IF v_session IS NULL THEN
    RETURN jsonb_build_object('ok', false);
  END IF;

  UPDATE public.client_portal_sessions
  SET last_seen_at = NOW()
  WHERE id = v_session.id;

  IF v_session.legacy_lead_id IS NOT NULL THEN
    SELECT public._portal_resolve_lead_ref(v_session.legacy_lead_id::TEXT) INTO v_lead;
  ELSE
    SELECT public._portal_resolve_lead_ref(v_session.new_lead_id::TEXT) INTO v_lead;
  END IF;

  SELECT jsonb_build_object(
    'id', lc.id,
    'name', lc.name,
    'email', lc.email
  ) INTO v_contact
  FROM public.leads_contact lc
  WHERE lc.id = v_session.contact_id;

  RETURN jsonb_build_object(
    'ok', true,
    'session_token', v_session.session_token,
    'lead_summary', v_lead,
    'contact', v_contact,
    'expires_at', v_session.expires_at
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_logout(p_token UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.client_portal_sessions WHERE session_token = p_token;
  RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_get_case_summary(p_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.client_portal_sessions;
  v_lead JSONB;
  v_expert_name TEXT;
  v_handler_name TEXT;
  v_scheduler_name TEXT;
  v_category TEXT;
BEGIN
  v_session := public._portal_session_row(p_token);
  IF v_session IS NULL THEN
    RETURN NULL;
  END IF;

  IF v_session.legacy_lead_id IS NOT NULL THEN
    SELECT public._portal_resolve_lead_ref(v_session.legacy_lead_id::TEXT) INTO v_lead;

    SELECT
      public._portal_role_display(public._portal_parse_employee_id(ll.expert_id::TEXT), NULL),
      public._portal_role_display(public._portal_parse_employee_id(ll.case_handler_id::TEXT), NULL),
      public._portal_role_display(public._portal_parse_employee_id(ll.meeting_scheduler_id::TEXT), NULL),
      mc.name
    INTO v_expert_name, v_handler_name, v_scheduler_name, v_category
    FROM public.leads_lead ll
    LEFT JOIN public.misc_category mc ON mc.id::TEXT = NULLIF(TRIM(ll.category_id::TEXT), '')
    WHERE ll.id = v_session.legacy_lead_id;
  ELSE
    SELECT public._portal_resolve_lead_ref(v_session.new_lead_id::TEXT) INTO v_lead;

    SELECT
      public._portal_role_display(public._portal_parse_employee_id(l.expert), l.expert),
      public._portal_role_display(
        COALESCE(
          public._portal_parse_employee_id(l.case_handler_id::TEXT),
          public._portal_parse_employee_id(l.handler)
        ),
        l.handler
      ),
      public._portal_role_display(public._portal_parse_employee_id(l.scheduler), l.scheduler),
      COALESCE(mc.name, NULLIF(TRIM(l.category::TEXT), ''))
    INTO v_expert_name, v_handler_name, v_scheduler_name, v_category
    FROM public.leads l
    LEFT JOIN public.misc_category mc ON mc.id::TEXT = NULLIF(TRIM(l.category_id::TEXT), '')
    WHERE l.id = v_session.new_lead_id;
  END IF;

  RETURN jsonb_build_object(
    'lead', v_lead,
    'expert_name', v_expert_name,
    'handler_name', v_handler_name,
    'scheduler_name', v_scheduler_name,
    'category', v_category
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_get_sub_efforts(p_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.client_portal_sessions;
  v_rows JSONB;
BEGIN
  v_session := public._portal_session_row(p_token);
  IF v_session IS NULL THEN
    RETURN NULL;
  END IF;

  IF v_session.legacy_lead_id IS NOT NULL THEN
    SELECT COALESCE(jsonb_agg(row_to_json(t)::JSONB ORDER BY t.created_at DESC), '[]'::JSONB)
    INTO v_rows
    FROM (
      SELECT
        lse.id,
        lse.sub_effort_id,
        se.name AS sub_effort_name,
        lse.active,
        lse.client_notes,
        lse.document_url,
        lse.created_at,
        lse.updated_at,
        lse.updated_by
      FROM public.lead_sub_efforts lse
      INNER JOIN public.sub_efforts se ON se.id = lse.sub_effort_id
      WHERE lse.legacy_lead_id::TEXT = v_session.legacy_lead_id::TEXT
        AND lse.internal = FALSE
        AND lse.active = TRUE
      ORDER BY lse.created_at DESC
    ) t;
  ELSE
    SELECT COALESCE(jsonb_agg(row_to_json(t)::JSONB ORDER BY t.created_at DESC), '[]'::JSONB)
    INTO v_rows
    FROM (
      SELECT
        lse.id,
        lse.sub_effort_id,
        se.name AS sub_effort_name,
        lse.active,
        lse.client_notes,
        lse.document_url,
        lse.created_at,
        lse.updated_at,
        lse.updated_by
      FROM public.lead_sub_efforts lse
      INNER JOIN public.sub_efforts se ON se.id = lse.sub_effort_id
      WHERE lse.new_lead_id::TEXT = v_session.new_lead_id::TEXT
        AND lse.internal = FALSE
        AND lse.active = TRUE
      ORDER BY lse.created_at DESC
    ) t;
  END IF;

  RETURN jsonb_build_object('rows', v_rows);
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_get_finances(p_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.client_portal_sessions;
  v_payments JSONB;
  v_proformas JSONB;
BEGIN
  v_session := public._portal_session_row(p_token);
  IF v_session IS NULL THEN
    RETURN NULL;
  END IF;

  IF v_session.legacy_lead_id IS NOT NULL THEN
    SELECT COALESCE(jsonb_agg(row_to_json(t)::JSONB ORDER BY t.due_date NULLS LAST, t.id), '[]'::JSONB)
    INTO v_payments
    FROM (
      SELECT
        fpr.id,
        fpr.date AS due_date,
        fpr.value,
        fpr.vat_value AS value_vat,
        (fpr.actual_date IS NOT NULL) AS paid,
        fpr.actual_date AS paid_at,
        fpr.client_id AS plan_contact_id,
        ac.name AS currency,
        pl.secure_token,
        pl.status AS link_status,
        pl.expires_at AS link_expires_at,
        TRUE AS is_legacy,
        NULL::TEXT AS public_token,
        NULL::BIGINT AS proforma_id,
        fpr."order" AS "order"
      FROM public.finances_paymentplanrow fpr
      LEFT JOIN public.accounting_currencies ac ON ac.id::TEXT = NULLIF(TRIM(fpr.currency_id::TEXT), '')
      LEFT JOIN LATERAL (
        SELECT pl2.secure_token, pl2.status, pl2.expires_at
        FROM public.payment_links pl2
        WHERE pl2.payment_plan_id::TEXT = fpr.id::TEXT
          AND pl2.is_legacy_payment_plan = TRUE
        ORDER BY pl2.created_at DESC
        LIMIT 1
      ) pl ON TRUE
      WHERE fpr.lead_id::TEXT = v_session.legacy_lead_id::TEXT
        AND fpr.cancel_date IS NULL
        AND (
          fpr.actual_date IS NOT NULL
          OR COALESCE(fpr.ready_to_pay, FALSE) = TRUE
        )
    ) t;

    SELECT COALESCE(jsonb_agg(row_to_json(t)::JSONB ORDER BY t.paid_at DESC NULLS LAST, t.id DESC), '[]'::JSONB)
    INTO v_proformas
    FROM (
      SELECT
        pi.id,
        pi.public_token,
        pi.created_at,
        TRUE AS is_legacy,
        fpr.actual_date AS paid_at,
        fpr.value,
        fpr.vat_value AS value_vat,
        ac.name AS currency
      FROM public.proformainvoice pi
      INNER JOIN public.finances_paymentplanrow fpr
        ON fpr.id = pi.ppr_id
       AND fpr.lead_id::TEXT = v_session.legacy_lead_id::TEXT
       AND fpr.cancel_date IS NULL
       AND fpr.actual_date IS NOT NULL
      LEFT JOIN public.accounting_currencies ac ON ac.id::TEXT = NULLIF(TRIM(fpr.currency_id::TEXT), '')
      WHERE pi.lead_id::TEXT = v_session.legacy_lead_id::TEXT
        AND pi.public_token IS NOT NULL
    ) t;
  ELSE
    SELECT COALESCE(jsonb_agg(row_to_json(t)::JSONB ORDER BY t.due_date NULLS LAST, t.id), '[]'::JSONB)
    INTO v_payments
    FROM (
      SELECT
        pp.id,
        pp.due_date,
        pp.value,
        pp.value_vat,
        COALESCE(pp.paid, FALSE) AS paid,
        pp.paid_at,
        pp.client_id AS plan_contact_id,
        COALESCE(pp.currency, ac.name, '₪') AS currency,
        pl.secure_token,
        pl.status AS link_status,
        pl.expires_at AS link_expires_at,
        FALSE AS is_legacy,
        pp.public_token,
        NULL::BIGINT AS proforma_id,
        pp.payment_order AS "order"
      FROM public.payment_plans pp
      LEFT JOIN public.accounting_currencies ac ON ac.id::TEXT = NULLIF(TRIM(pp.currency_id::TEXT), '')
      LEFT JOIN LATERAL (
        SELECT pl2.secure_token, pl2.status, pl2.expires_at
        FROM public.payment_links pl2
        WHERE pl2.payment_plan_id::TEXT = pp.id::TEXT
        ORDER BY pl2.created_at DESC
        LIMIT 1
      ) pl ON TRUE
      WHERE pp.lead_id::TEXT = v_session.new_lead_id::TEXT
        AND pp.cancel_date IS NULL
        AND (
          COALESCE(pp.paid, FALSE) = TRUE
          OR COALESCE(pp.ready_to_pay, FALSE) = TRUE
        )
    ) t;

    v_proformas := '[]'::JSONB;
  END IF;

  RETURN jsonb_build_object(
    'payments', v_payments,
    'proformas', v_proformas,
    'is_legacy', v_session.legacy_lead_id IS NOT NULL
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_get_documents(p_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.client_portal_sessions;
  v_lead_number TEXT;
  v_docs JSONB;
BEGIN
  v_session := public._portal_session_row(p_token);
  IF v_session IS NULL THEN
    RETURN NULL;
  END IF;

  IF v_session.legacy_lead_id IS NOT NULL THEN
    SELECT COALESCE(NULLIF(TRIM(ll.lead_number::TEXT), ''), ll.id::TEXT)
    INTO v_lead_number
    FROM public.leads_lead ll
    WHERE ll.id = v_session.legacy_lead_id;
  ELSE
    SELECT COALESCE(NULLIF(TRIM(l.lead_number::TEXT), ''), NULLIF(TRIM(l.manual_id::TEXT), ''), l.id::TEXT)
    INTO v_lead_number
    FROM public.leads l
    WHERE l.id = v_session.new_lead_id;
  END IF;

  SELECT COALESCE(jsonb_agg(row_to_json(t)::JSONB ORDER BY t.created_at DESC), '[]'::JSONB)
  INTO v_docs
  FROM (
    SELECT
      d.id,
      d.file_name,
      d.storage_path,
      d.mime_type,
      d.file_size,
      d.created_at,
      d.onedrive_subfolder
    FROM public.lead_case_documents d
    WHERE d.lead_number = v_lead_number
      AND (d.onedrive_subfolder IS NULL OR d.onedrive_subfolder NOT ILIKE '%internal%')
    ORDER BY d.created_at DESC
  ) t;

  RETURN jsonb_build_object('documents', v_docs, 'lead_number', v_lead_number);
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_prepare_document_upload(
  p_token UUID,
  p_file_name TEXT,
  p_mime_type TEXT DEFAULT NULL,
  p_file_size BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.client_portal_sessions;
  v_lead_number TEXT;
  v_safe_name TEXT;
  v_storage_path TEXT;
  v_upload_id BIGINT;
BEGIN
  v_session := public._portal_session_row(p_token);
  IF v_session IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Session expired');
  END IF;

  IF p_file_name IS NULL OR trim(p_file_name) = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'File name required');
  END IF;

  IF v_session.legacy_lead_id IS NOT NULL THEN
    SELECT COALESCE(NULLIF(TRIM(ll.lead_number::TEXT), ''), ll.id::TEXT)
    INTO v_lead_number
    FROM public.leads_lead ll
    WHERE ll.id = v_session.legacy_lead_id;
  ELSE
    SELECT COALESCE(NULLIF(TRIM(l.lead_number::TEXT), ''), NULLIF(TRIM(l.manual_id::TEXT), ''), l.id::TEXT)
    INTO v_lead_number
    FROM public.leads l
    WHERE l.id = v_session.new_lead_id;
  END IF;

  v_safe_name := regexp_replace(trim(p_file_name), '[^\w.\-()+ ]', '_', 'g');
  v_storage_path := format(
    'case-documents/%s/portal-client/%s_%s',
    v_lead_number,
    extract(epoch from now())::BIGINT,
    v_safe_name
  );

  INSERT INTO public.client_portal_upload_tokens (
    session_id, storage_path, file_name, mime_type, file_size, expires_at
  ) VALUES (
    v_session.id, v_storage_path, trim(p_file_name), p_mime_type, p_file_size, NOW() + INTERVAL '1 hour'
  )
  RETURNING id INTO v_upload_id;

  RETURN jsonb_build_object(
    'ok', true,
    'upload_id', v_upload_id,
    'storage_path', v_storage_path,
    'lead_number', v_lead_number,
    'bucket', 'lead-sub-efforts-documents'
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_finalize_document_upload(
  p_token UUID,
  p_storage_path TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.client_portal_sessions;
  v_token_row public.client_portal_upload_tokens;
  v_doc_id BIGINT;
  v_lead_number TEXT;
BEGIN
  v_session := public._portal_session_row(p_token);
  IF v_session IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Session expired');
  END IF;

  SELECT * INTO v_token_row
  FROM public.client_portal_upload_tokens t
  WHERE t.session_id = v_session.id
    AND t.storage_path = p_storage_path
    AND t.used = FALSE
    AND t.expires_at > NOW()
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Invalid upload token');
  END IF;

  IF v_session.legacy_lead_id IS NOT NULL THEN
    SELECT COALESCE(NULLIF(TRIM(ll.lead_number::TEXT), ''), ll.id::TEXT)
    INTO v_lead_number
    FROM public.leads_lead ll
    WHERE ll.id = v_session.legacy_lead_id;
  ELSE
    SELECT COALESCE(NULLIF(TRIM(l.lead_number::TEXT), ''), NULLIF(TRIM(l.manual_id::TEXT), ''), l.id::TEXT)
    INTO v_lead_number
    FROM public.leads l
    WHERE l.id = v_session.new_lead_id;
  END IF;

  INSERT INTO public.lead_case_documents (
    lead_number,
    onedrive_subfolder,
    storage_path,
    file_name,
    file_size,
    mime_type,
    uploaded_by,
    ai_summary_status
  ) VALUES (
    v_lead_number,
    'portal-client',
    v_token_row.storage_path,
    v_token_row.file_name,
    v_token_row.file_size,
    COALESCE(v_token_row.mime_type, 'application/octet-stream'),
    'portal-client',
    'skipped'
  )
  RETURNING id INTO v_doc_id;

  UPDATE public.client_portal_upload_tokens
  SET used = TRUE
  WHERE id = v_token_row.id;

  RETURN jsonb_build_object('ok', true, 'document_id', v_doc_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_get_contacts(p_token UUID)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.client_portal_sessions;
  v_contacts JSONB;
BEGIN
  v_session := public._portal_session_row(p_token);
  IF v_session IS NULL THEN
    RETURN NULL;
  END IF;

  IF v_session.legacy_lead_id IS NOT NULL THEN
    SELECT COALESCE(jsonb_agg(row_to_json(t)::JSONB ORDER BY t.is_main DESC, t.id), '[]'::JSONB)
    INTO v_contacts
    FROM (
      SELECT
        lc.id,
        lc.name,
        lc.mobile,
        lc.phone,
        lc.email,
        lc.address,
        lc.country_id,
        (llc.main::TEXT IN ('true', 't', '1')) AS is_main
      FROM public.lead_leadcontact llc
      INNER JOIN public.leads_contact lc ON lc.id::TEXT = llc.contact_id::TEXT
      WHERE llc.lead_id::TEXT = v_session.legacy_lead_id::TEXT
    ) t;
  ELSE
    SELECT COALESCE(jsonb_agg(row_to_json(t)::JSONB ORDER BY t.is_main DESC, t.id), '[]'::JSONB)
    INTO v_contacts
    FROM (
      SELECT
        lc.id,
        lc.name,
        lc.mobile,
        lc.phone,
        lc.email,
        lc.address,
        lc.country_id,
        (llc.main::TEXT IN ('true', 't', '1')) AS is_main
      FROM public.lead_leadcontact llc
      INNER JOIN public.leads_contact lc ON lc.id::TEXT = llc.contact_id::TEXT
      WHERE llc.newlead_id::TEXT = v_session.new_lead_id::TEXT

      UNION ALL

      SELECT
        lc.id,
        lc.name,
        lc.mobile,
        lc.phone,
        lc.email,
        lc.address,
        lc.country_id,
        FALSE AS is_main
      FROM public.leads_contact lc
      WHERE lc.newlead_id::TEXT = v_session.new_lead_id::TEXT
        AND NOT EXISTS (
          SELECT 1
          FROM public.lead_leadcontact llc
          WHERE llc.contact_id::TEXT = lc.id::TEXT
            AND llc.newlead_id::TEXT = v_session.new_lead_id::TEXT
        )
    ) t;
  END IF;

  RETURN jsonb_build_object('contacts', v_contacts);
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_update_contact(
  p_token UUID,
  p_contact_id BIGINT,
  p_fields JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.client_portal_sessions;
  v_on_lead BOOLEAN := FALSE;
BEGIN
  v_session := public._portal_session_row(p_token);
  IF v_session IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Session expired');
  END IF;

  IF v_session.legacy_lead_id IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM public.lead_leadcontact llc
      WHERE llc.contact_id::TEXT = p_contact_id::TEXT AND llc.lead_id::TEXT = v_session.legacy_lead_id::TEXT
    ) INTO v_on_lead;
  ELSE
    SELECT (
      EXISTS (
        SELECT 1 FROM public.lead_leadcontact llc
        WHERE llc.contact_id::TEXT = p_contact_id::TEXT
          AND llc.newlead_id::TEXT = v_session.new_lead_id::TEXT
      )
      OR EXISTS (
        SELECT 1 FROM public.leads_contact lc
        WHERE lc.id = p_contact_id AND lc.newlead_id::TEXT = v_session.new_lead_id::TEXT
      )
    ) INTO v_on_lead;
  END IF;

  IF NOT v_on_lead THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Contact not found');
  END IF;

  UPDATE public.leads_contact lc
  SET
    name = COALESCE(NULLIF(trim(p_fields->>'name'), ''), lc.name),
    mobile = CASE WHEN p_fields ? 'mobile' THEN NULLIF(trim(p_fields->>'mobile'), '') ELSE lc.mobile END,
    phone = CASE WHEN p_fields ? 'phone' THEN NULLIF(trim(p_fields->>'phone'), '') ELSE lc.phone END,
    email = CASE WHEN p_fields ? 'email' THEN NULLIF(trim(p_fields->>'email'), '') ELSE lc.email END,
    address = CASE WHEN p_fields ? 'address' THEN NULLIF(trim(p_fields->>'address'), '') ELSE lc.address END,
    country_id = CASE
      WHEN p_fields ? 'country_id' AND (p_fields->>'country_id') ~ '^\d+$'
      THEN (p_fields->>'country_id')::BIGINT
      ELSE lc.country_id
    END,
    udate = CURRENT_DATE
  WHERE lc.id = p_contact_id;

  RETURN jsonb_build_object('ok', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_create_meeting_request(
  p_token UUID,
  p_payload JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.client_portal_sessions;
  v_id BIGINT;
  v_date DATE;
BEGIN
  v_session := public._portal_session_row(p_token);
  IF v_session IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Session expired');
  END IF;

  v_date := (p_payload->>'preferred_date')::DATE;
  IF v_date IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Preferred date is required');
  END IF;

  INSERT INTO public.client_portal_meeting_requests (
    contact_id,
    new_lead_id,
    legacy_lead_id,
    preferred_date,
    preferred_time_range,
    notes,
    status
  ) VALUES (
    v_session.contact_id,
    v_session.new_lead_id,
    v_session.legacy_lead_id,
    v_date,
    NULLIF(trim(p_payload->>'preferred_time_range'), ''),
    NULLIF(trim(p_payload->>'notes'), ''),
    'pending'
  )
  RETURNING id INTO v_id;

  RETURN jsonb_build_object('ok', true, 'id', v_id);
END;
$$;

-- ---------------------------------------------------------------------------
-- Staff RPCs (authenticated)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.portal_staff_set_password(
  p_lead_id TEXT,
  p_lead_type TEXT,
  p_password TEXT,
  p_enabled BOOLEAN DEFAULT TRUE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_new_lead_id UUID;
  v_legacy_lead_id BIGINT;
  v_hash TEXT;
  v_row public.client_portal_access;
BEGIN
  IF p_password IS NULL OR length(trim(p_password)) < 6 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Password must be at least 6 characters');
  END IF;

  v_hash := public.portal_hash_password(p_password);

  IF lower(coalesce(p_lead_type, '')) = 'legacy' OR p_lead_id ~ '^legacy_' OR p_lead_id ~ '^\d+$' THEN
    v_legacy_lead_id := regexp_replace(p_lead_id, '^legacy_', '')::BIGINT;
    UPDATE public.client_portal_access
    SET
      password_hash = v_hash,
      enabled = COALESCE(p_enabled, TRUE),
      updated_at = NOW(),
      updated_by = auth.uid()::TEXT
    WHERE legacy_lead_id = v_legacy_lead_id
    RETURNING * INTO v_row;

    IF NOT FOUND THEN
      INSERT INTO public.client_portal_access (legacy_lead_id, password_hash, enabled, updated_by)
      VALUES (v_legacy_lead_id, v_hash, COALESCE(p_enabled, TRUE), auth.uid()::TEXT)
      RETURNING * INTO v_row;
    END IF;
  ELSE
    v_new_lead_id := p_lead_id::UUID;
    UPDATE public.client_portal_access
    SET
      password_hash = v_hash,
      enabled = COALESCE(p_enabled, TRUE),
      updated_at = NOW(),
      updated_by = auth.uid()::TEXT
    WHERE new_lead_id = v_new_lead_id
    RETURNING * INTO v_row;

    IF NOT FOUND THEN
      INSERT INTO public.client_portal_access (new_lead_id, password_hash, enabled, updated_by)
      VALUES (v_new_lead_id, v_hash, COALESCE(p_enabled, TRUE), auth.uid()::TEXT)
      RETURNING * INTO v_row;
    END IF;
  END IF;

  RETURN jsonb_build_object('ok', true, 'enabled', v_row.enabled, 'updated_at', v_row.updated_at);
END;
$$;

CREATE OR REPLACE FUNCTION public.portal_staff_get_status(
  p_lead_id TEXT,
  p_lead_type TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.client_portal_access;
  v_lead_ref TEXT;
BEGIN
  IF lower(coalesce(p_lead_type, '')) = 'legacy' OR p_lead_id ~ '^legacy_' OR (p_lead_id ~ '^\d+$' AND length(p_lead_id) < 20) THEN
    SELECT * INTO v_row
    FROM public.client_portal_access
    WHERE legacy_lead_id = regexp_replace(p_lead_id, '^legacy_', '')::BIGINT
    LIMIT 1;

    SELECT COALESCE(NULLIF(TRIM(lead_number::TEXT), ''), id::TEXT)
    INTO v_lead_ref
    FROM public.leads_lead
    WHERE id = regexp_replace(p_lead_id, '^legacy_', '')::BIGINT;
  ELSE
    SELECT * INTO v_row
    FROM public.client_portal_access
    WHERE new_lead_id = p_lead_id::UUID
    LIMIT 1;

    SELECT COALESCE(NULLIF(TRIM(lead_number::TEXT), ''), NULLIF(TRIM(manual_id::TEXT), ''), id::TEXT)
    INTO v_lead_ref
    FROM public.leads
    WHERE id = p_lead_id::UUID;
  END IF;

  IF NOT FOUND OR v_row IS NULL THEN
    RETURN jsonb_build_object('enabled', true, 'has_password', false, 'lead_ref', v_lead_ref);
  END IF;

  RETURN jsonb_build_object(
    'enabled', v_row.enabled,
    'has_password', v_row.password_hash IS NOT NULL,
    'updated_at', v_row.updated_at,
    'lead_ref', v_lead_ref
  );
END;
$$;

-- Storage: allow anon upload to portal-client paths with valid upload token
DROP POLICY IF EXISTS "portal-client upload policy" ON storage.objects;
CREATE POLICY "portal-client upload policy" ON storage.objects
FOR INSERT TO anon, authenticated
WITH CHECK (
  bucket_id = 'lead-sub-efforts-documents'
  AND name LIKE 'case-documents/%/portal-client/%'
  AND EXISTS (
    SELECT 1 FROM public.client_portal_upload_tokens t
    WHERE t.storage_path = name
      AND t.used = FALSE
      AND t.expires_at > NOW()
  )
);

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

GRANT EXECUTE ON FUNCTION public.portal_login(TEXT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_validate_session(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_logout(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_get_case_summary(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_get_sub_efforts(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_get_finances(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_get_documents(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_prepare_document_upload(UUID, TEXT, TEXT, BIGINT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_finalize_document_upload(UUID, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_get_contacts(UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_update_contact(UUID, BIGINT, JSONB) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_create_meeting_request(UUID, JSONB) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.portal_staff_set_password(TEXT, TEXT, TEXT, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.portal_staff_get_status(TEXT, TEXT) TO authenticated;
