-- =============================================================================
-- source_media_expense: monthly media spend per lead source (misc_leadsource)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.source_media_expense (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lead_source_id bigint NOT NULL,
    expense_month date NOT NULL,
    amount numeric(14, 2) NOT NULL CHECK (amount >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NULL,
    CONSTRAINT pk_source_media_expense PRIMARY KEY (id),
    CONSTRAINT source_media_expense_lead_source_id_fkey
        FOREIGN KEY (lead_source_id)
        REFERENCES public.misc_leadsource (id)
        ON DELETE RESTRICT,
    CONSTRAINT source_media_expense_created_by_fkey
        FOREIGN KEY (created_by)
        REFERENCES auth.users (id)
        ON DELETE SET NULL,
    CONSTRAINT source_media_expense_lead_source_month_key
        UNIQUE (lead_source_id, expense_month),
    CONSTRAINT source_media_expense_month_first_day_chk
        CHECK (date_trunc('month', expense_month::timestamp)::date = expense_month)
);

COMMENT ON TABLE public.source_media_expense IS 'Monthly marketing/media spend per lead source.';
COMMENT ON COLUMN public.source_media_expense.expense_month IS 'First calendar day of the month (YYYY-MM-01).';
COMMENT ON COLUMN public.source_media_expense.amount IS 'Expense amount (typically NIS).';

CREATE INDEX IF NOT EXISTS idx_source_media_expense_lead_source_id
    ON public.source_media_expense (lead_source_id);

CREATE INDEX IF NOT EXISTS idx_source_media_expense_expense_month
    ON public.source_media_expense (expense_month DESC);

CREATE OR REPLACE FUNCTION public.set_source_media_expense_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.created_by IS NULL THEN
            NEW.created_by := auth.uid();
        END IF;
        IF NEW.created_at IS NULL THEN
            NEW.created_at := now();
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_source_media_expense_audit ON public.source_media_expense;
CREATE TRIGGER trg_source_media_expense_audit
    BEFORE INSERT ON public.source_media_expense
    FOR EACH ROW
    EXECUTE FUNCTION public.set_source_media_expense_audit();

ALTER TABLE public.source_media_expense ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can view source media expenses" ON public.source_media_expense;
CREATE POLICY "Authenticated users can view source media expenses"
    ON public.source_media_expense
    FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert source media expenses" ON public.source_media_expense;
CREATE POLICY "Authenticated users can insert source media expenses"
    ON public.source_media_expense
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated users can update source media expenses" ON public.source_media_expense;
CREATE POLICY "Authenticated users can update source media expenses"
    ON public.source_media_expense
    FOR UPDATE
    TO authenticated
    USING (auth.uid() IS NOT NULL)
    WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated users can delete source media expenses" ON public.source_media_expense;
CREATE POLICY "Authenticated users can delete source media expenses"
    ON public.source_media_expense
    FOR DELETE
    TO authenticated
    USING (auth.uid() IS NOT NULL);
