-- Preset workplaces for clock-in/out (user picks from dropdown; GPS is stored separately on employee_clock_in).
-- Run after sql/create_employee_clock_in_table.sql

CREATE TABLE IF NOT EXISTS public.clock_in_locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    slug text,
    sort_order integer DEFAULT 0 NOT NULL,
    active boolean DEFAULT true NOT NULL,
    CONSTRAINT clock_in_locations_pkey PRIMARY KEY (id),
    CONSTRAINT clock_in_locations_name_key UNIQUE (name),
    CONSTRAINT clock_in_locations_slug_key UNIQUE (slug)
);

COMMENT ON TABLE public.clock_in_locations IS 'Preset workplaces employees select when clocking in/out (Ramat Gan, Jerusalem, Home, etc.)';

-- Seed the three default workplaces (idempotent)
INSERT INTO public.clock_in_locations (name, slug, sort_order, active)
VALUES
    ('Ramat Gan - Office', 'ramat-gan-office', 10, true),
    ('Jerusalem - Office', 'jerusalem-office', 20, true),
    ('Home', 'home', 30, true)
ON CONFLICT (name) DO UPDATE SET
    slug = EXCLUDED.slug,
    sort_order = EXCLUDED.sort_order,
    active = EXCLUDED.active;

-- Link employee_clock_in to the selected preset (separate from GPS columns)
ALTER TABLE public.employee_clock_in
    ADD COLUMN IF NOT EXISTS clock_in_location_id bigint,
    ADD COLUMN IF NOT EXISTS clock_out_location_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'employee_clock_in_clock_in_location_id_fkey'
    ) THEN
        ALTER TABLE public.employee_clock_in
            ADD CONSTRAINT employee_clock_in_clock_in_location_id_fkey
            FOREIGN KEY (clock_in_location_id) REFERENCES public.clock_in_locations(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'employee_clock_in_clock_out_location_id_fkey'
    ) THEN
        ALTER TABLE public.employee_clock_in
            ADD CONSTRAINT employee_clock_in_clock_out_location_id_fkey
            FOREIGN KEY (clock_out_location_id) REFERENCES public.clock_in_locations(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_employee_clock_in_clock_in_location_id
    ON public.employee_clock_in(clock_in_location_id);
CREATE INDEX IF NOT EXISTS idx_employee_clock_in_clock_out_location_id
    ON public.employee_clock_in(clock_out_location_id);

COMMENT ON COLUMN public.employee_clock_in.clock_in_location_id IS 'User-selected preset workplace at clock-in';
COMMENT ON COLUMN public.employee_clock_in.clock_out_location_id IS 'User-selected preset workplace at clock-out';

ALTER TABLE public.clock_in_locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read active clock-in locations" ON public.clock_in_locations;
CREATE POLICY "Authenticated users can read active clock-in locations"
ON public.clock_in_locations FOR SELECT
TO authenticated
USING (active = true);
