-- DEPRECATED: use sql/create_boi_exchange_rates_table.sql instead.
-- This file previously created public.currency_rates and overwrote existing objects.
-- BOI daily rates now live in public.boi_exchange_rates (separate from your existing currency_rates table).
