-- Monthly working-hours submissions (one row per employee per calendar month).
-- Run after tenants_employee and users exist.

CREATE TABLE IF NOT EXISTS public.employee_working_hours_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    employee_id bigint NOT NULL,
    user_id uuid NOT NULL,
    year integer NOT NULL CHECK (year >= 2000 AND year <= 2100),
    month integer NOT NULL CHECK (month >= 1 AND month <= 12),
    period_total text,
    missing_days integer DEFAULT 0 NOT NULL CHECK (missing_days >= 0),
    submitted_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT employee_working_hours_submissions_pkey PRIMARY KEY (id),
    CONSTRAINT employee_working_hours_submissions_employee_id_fkey
        FOREIGN KEY (employee_id) REFERENCES public.tenants_employee(id) ON DELETE CASCADE,
    CONSTRAINT employee_working_hours_submissions_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT employee_working_hours_submissions_employee_year_month_key
        UNIQUE (employee_id, year, month)
);

CREATE INDEX IF NOT EXISTS idx_employee_working_hours_submissions_employee
    ON public.employee_working_hours_submissions(employee_id);

CREATE INDEX IF NOT EXISTS idx_employee_working_hours_submissions_year_month
    ON public.employee_working_hours_submissions(year, month);

COMMENT ON TABLE public.employee_working_hours_submissions IS
    'Tracks once-per-month working hours submissions by employees';

ALTER TABLE public.employee_working_hours_submissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Employees can view own working hours submissions"
    ON public.employee_working_hours_submissions;
CREATE POLICY "Employees can view own working hours submissions"
ON public.employee_working_hours_submissions FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.auth_id = auth.uid()
          AND u.employee_id = employee_working_hours_submissions.employee_id
    )
);

DROP POLICY IF EXISTS "Employees can submit own working hours once per month"
    ON public.employee_working_hours_submissions;
CREATE POLICY "Employees can submit own working hours once per month"
ON public.employee_working_hours_submissions FOR INSERT
TO authenticated
WITH CHECK (
    auth.uid() = user_id
    AND EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.auth_id = auth.uid()
          AND u.employee_id = employee_working_hours_submissions.employee_id
    )
);

DROP POLICY IF EXISTS "Superusers can view all working hours submissions"
    ON public.employee_working_hours_submissions;
CREATE POLICY "Superusers can view all working hours submissions"
ON public.employee_working_hours_submissions FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.auth_id = auth.uid()
          AND (
              u.is_superuser IS TRUE
              OR u.is_superuser::text IN ('true', 't', '1')
          )
    )
);
