-- =============================================================================
-- partner_draw_expense: monthly partner draw amount per employee (NIS)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.partner_draw_expense (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id bigint NOT NULL,
    expense_month date NOT NULL,
    amount_nis numeric(14, 2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NULL,
    CONSTRAINT pk_partner_draw_expense PRIMARY KEY (id),
    CONSTRAINT partner_draw_expense_employee_id_fkey
        FOREIGN KEY (employee_id)
        REFERENCES public.tenants_employee (id)
        ON DELETE RESTRICT,
    CONSTRAINT partner_draw_expense_created_by_fkey
        FOREIGN KEY (created_by)
        REFERENCES auth.users (id)
        ON DELETE SET NULL,
    CONSTRAINT partner_draw_expense_employee_month_key
        UNIQUE (employee_id, expense_month),
    CONSTRAINT partner_draw_expense_amount_nis_chk
        CHECK (amount_nis >= 0),
    CONSTRAINT partner_draw_expense_month_first_day_chk
        CHECK (date_trunc('month', expense_month::timestamp)::date = expense_month)
);

COMMENT ON TABLE public.partner_draw_expense IS 'Monthly partner draw amounts in NIS per employee.';
COMMENT ON COLUMN public.partner_draw_expense.expense_month IS 'First calendar day of the month (YYYY-MM-01).';
COMMENT ON COLUMN public.partner_draw_expense.amount_nis IS 'Draw amount in Israeli shekels (NIS).';

CREATE INDEX IF NOT EXISTS idx_partner_draw_expense_employee_id
    ON public.partner_draw_expense (employee_id);

CREATE INDEX IF NOT EXISTS idx_partner_draw_expense_expense_month
    ON public.partner_draw_expense (expense_month DESC);

CREATE OR REPLACE FUNCTION public.set_partner_draw_expense_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.created_by IS NULL THEN
            NEW.created_by := auth.uid();
        END IF;
        IF NEW.created_at IS NULL THEN
            NEW.created_at := now();
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_partner_draw_expense_audit ON public.partner_draw_expense;
CREATE TRIGGER trg_partner_draw_expense_audit
    BEFORE INSERT ON public.partner_draw_expense
    FOR EACH ROW
    EXECUTE FUNCTION public.set_partner_draw_expense_audit();

ALTER TABLE public.partner_draw_expense ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "partner_draw_expense_select" ON public.partner_draw_expense;
CREATE POLICY "partner_draw_expense_select" ON public.partner_draw_expense FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "partner_draw_expense_insert" ON public.partner_draw_expense;
CREATE POLICY "partner_draw_expense_insert" ON public.partner_draw_expense FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "partner_draw_expense_update" ON public.partner_draw_expense;
CREATE POLICY "partner_draw_expense_update" ON public.partner_draw_expense FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "partner_draw_expense_delete" ON public.partner_draw_expense;
CREATE POLICY "partner_draw_expense_delete" ON public.partner_draw_expense FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.partner_draw_expense TO authenticated;
