-- Create employee_clock_in table to track clock-in/clock-out times
CREATE TABLE IF NOT EXISTS public.employee_clock_in (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    employee_id bigint NOT NULL,
    user_id uuid NOT NULL, -- Reference to auth.users for the employee
    clock_in_time timestamp with time zone NOT NULL,
    clock_out_time timestamp with time zone,
    location_latitude numeric(10, 8), -- GPS latitude
    location_longitude numeric(11, 8), -- GPS longitude
    location_address text, -- Human-readable address from reverse geocoding
    location_city text,
    location_country text,
    location_source text DEFAULT 'browser', -- 'browser' or 'ip' or 'manual'
    notes text, -- Optional notes for clock-in/out
    is_active boolean DEFAULT true NOT NULL, -- True if currently clocked in (no clock_out_time)
    CONSTRAINT employee_clock_in_pkey PRIMARY KEY (id),
    CONSTRAINT employee_clock_in_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.tenants_employee(id) ON DELETE CASCADE,
    CONSTRAINT employee_clock_in_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT employee_clock_in_time_check CHECK (clock_out_time IS NULL OR clock_out_time >= clock_in_time)
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_employee_clock_in_employee_id ON public.employee_clock_in(employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_clock_in_user_id ON public.employee_clock_in(user_id);
CREATE INDEX IF NOT EXISTS idx_employee_clock_in_clock_in_time ON public.employee_clock_in(clock_in_time DESC);
CREATE INDEX IF NOT EXISTS idx_employee_clock_in_is_active ON public.employee_clock_in(is_active) WHERE is_active = true;
-- Note: Date-based queries can use the clock_in_time index efficiently with date range filters

-- Enable RLS
ALTER TABLE public.employee_clock_in ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Users can view their own clock-in records
CREATE POLICY "Users can view their own clock-in records" 
ON public.employee_clock_in FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

-- Users can insert their own clock-in records
CREATE POLICY "Users can insert their own clock-in records" 
ON public.employee_clock_in FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- Users can update their own clock-in records (for clock-out)
CREATE POLICY "Users can update their own clock-in records" 
ON public.employee_clock_in FOR UPDATE 
TO authenticated 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Superusers/admins can view all records (optional - adjust based on your needs)
-- CREATE POLICY "Admins can view all clock-in records" 
-- ON public.employee_clock_in FOR SELECT 
-- TO authenticated 
-- USING (
--   EXISTS (
--     SELECT 1 FROM public.users 
--     WHERE id = auth.uid() 
--     AND is_superuser = true
--   )
-- );

-- Add comments
COMMENT ON TABLE public.employee_clock_in IS 'Tracks employee clock-in and clock-out times with location data';
COMMENT ON COLUMN public.employee_clock_in.employee_id IS 'Reference to tenants_employee table';
COMMENT ON COLUMN public.employee_clock_in.user_id IS 'Reference to auth.users for authentication';
COMMENT ON COLUMN public.employee_clock_in.clock_in_time IS 'Timestamp when employee clocked in';
COMMENT ON COLUMN public.employee_clock_in.clock_out_time IS 'Timestamp when employee clocked out (NULL if still clocked in)';
COMMENT ON COLUMN public.employee_clock_in.location_latitude IS 'GPS latitude of clock-in location';
COMMENT ON COLUMN public.employee_clock_in.location_longitude IS 'GPS longitude of clock-in location';
COMMENT ON COLUMN public.employee_clock_in.location_address IS 'Human-readable address from reverse geocoding';
COMMENT ON COLUMN public.employee_clock_in.is_active IS 'True if employee is currently clocked in (no clock_out_time)';
