-- Create employee_salary table to store salary data extracted from payroll documents
CREATE TABLE IF NOT EXISTS public.employee_salary (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    employee_id bigint NOT NULL,
    worker_id text, -- The employee number from the payroll document
    salary_month integer NOT NULL, -- 1-12
    salary_year integer NOT NULL, -- e.g., 2025
    gross_salary numeric(12,2) NOT NULL, -- סה״כ משכורת ברוטו
    net_salary numeric(12,2), -- סה״כ משכורת נטו (optional)
    document_url text, -- URL to the uploaded PDF document
    extracted_data jsonb, -- Store raw extracted data for audit
    approved boolean DEFAULT false NOT NULL, -- Approval flag for payroll import
    approved_by uuid, -- User who approved
    approved_at timestamp with time zone,
    uploaded_by uuid NOT NULL, -- User who uploaded
    CONSTRAINT employee_salary_pkey PRIMARY KEY (id),
    CONSTRAINT employee_salary_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.tenants_employee(id) ON DELETE CASCADE,
    CONSTRAINT employee_salary_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT employee_salary_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT employee_salary_month_check CHECK (salary_month >= 1 AND salary_month <= 12),
    CONSTRAINT employee_salary_year_check CHECK (salary_year >= 2000 AND salary_year <= 2100),
    CONSTRAINT employee_salary_unique_period UNIQUE (employee_id, salary_month, salary_year)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_employee_salary_employee_id ON public.employee_salary(employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_salary_period ON public.employee_salary(salary_year, salary_month);
CREATE INDEX IF NOT EXISTS idx_employee_salary_worker_id ON public.employee_salary(worker_id);

-- Enable RLS
ALTER TABLE public.employee_salary ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Allow authenticated users to read employee salary" 
ON public.employee_salary FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Allow authenticated users to insert employee salary" 
ON public.employee_salary FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update employee salary" 
ON public.employee_salary FOR UPDATE 
TO authenticated 
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete employee salary" 
ON public.employee_salary FOR DELETE 
TO authenticated 
USING (true);

-- Add comment
COMMENT ON TABLE public.employee_salary IS 'Stores employee salary data extracted from payroll documents';
COMMENT ON COLUMN public.employee_salary.worker_id IS 'Employee number from payroll document (מספר עובד)';
COMMENT ON COLUMN public.employee_salary.gross_salary IS 'Gross salary amount (סה״כ משכורת ברוטו)';
COMMENT ON COLUMN public.employee_salary.extracted_data IS 'Raw extracted data from PDF for audit purposes';
COMMENT ON COLUMN public.employee_salary.approved IS 'Whether the salary import has been approved';
