-- =============================================================================
-- Lookup table for user_content_flags.flag_type (bigint FK).
-- Run before alter_user_content_flags_add_flag_type.sql
-- Safe to re-run: IF NOT EXISTS + upsert seeds.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.flag_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  label text NOT NULL
);

COMMENT ON TABLE public.flag_types IS 'IDs only — referenced by user_content_flags.flag_type (e.g. probability, referral).';

INSERT INTO public.flag_types (id, code, label) VALUES
  (1, 'probability', 'Probability'),
  (2, 'referral', 'Referral')
ON CONFLICT (id) DO UPDATE SET
  code = EXCLUDED.code,
  label = EXCLUDED.label;

-- Keep identity in sync after explicit ids
SELECT setval(
  pg_get_serial_sequence('public.flag_types', 'id'),
  COALESCE((SELECT MAX(id) FROM public.flag_types), 1)
);

ALTER TABLE public.flag_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can read flag_types" ON public.flag_types;
CREATE POLICY "Authenticated users can read flag_types"
  ON public.flag_types FOR SELECT
  TO authenticated
  USING (true);

GRANT SELECT ON TABLE public.flag_types TO authenticated;
GRANT ALL ON TABLE public.flag_types TO service_role;
