-- Create table for user highlights/bookmarks
CREATE TABLE IF NOT EXISTS public.user_highlights (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  lead_id bigint null,
  new_lead_id uuid null,
  lead_number text null,
  constraint user_highlights_pkey primary key (id),
  constraint user_highlights_user_id_fkey foreign KEY (user_id) references users (id) on delete cascade,
  constraint user_highlights_lead_id_fkey foreign KEY (lead_id) references leads_lead (id) on delete cascade,
  constraint user_highlights_new_lead_id_fkey foreign KEY (new_lead_id) references leads (id) on delete cascade,
  constraint user_highlights_unique_user_lead unique (user_id, lead_id, new_lead_id)
) TABLESPACE pg_default;

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_user_highlights_user_id ON public.user_highlights USING btree (user_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_user_highlights_lead_id ON public.user_highlights USING btree (lead_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_user_highlights_new_lead_id ON public.user_highlights USING btree (new_lead_id) TABLESPACE pg_default;

-- Add RLS policies
ALTER TABLE public.user_highlights ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see their own highlights
CREATE POLICY "Users can view their own highlights"
  ON public.user_highlights
  FOR SELECT
  USING (auth.uid() IN (SELECT auth_id FROM users WHERE id = user_highlights.user_id));

-- Policy: Users can insert their own highlights
CREATE POLICY "Users can insert their own highlights"
  ON public.user_highlights
  FOR INSERT
  WITH CHECK (auth.uid() IN (SELECT auth_id FROM users WHERE id = user_highlights.user_id));

-- Policy: Users can delete their own highlights
CREATE POLICY "Users can delete their own highlights"
  ON public.user_highlights
  FOR DELETE
  USING (auth.uid() IN (SELECT auth_id FROM users WHERE id = user_highlights.user_id));

