-- =============================================================================
-- Office rent: rent_offices (locations) + office_rent_expense (monthly NIS per office)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.rent_offices (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NULL,
    CONSTRAINT pk_rent_offices PRIMARY KEY (id),
    CONSTRAINT rent_offices_name_key UNIQUE (name),
    CONSTRAINT rent_offices_created_by_fkey
        FOREIGN KEY (created_by)
        REFERENCES auth.users (id)
        ON DELETE SET NULL
);

COMMENT ON TABLE public.rent_offices IS 'Office / branch locations for monthly rent tracking.';
COMMENT ON COLUMN public.rent_offices.sort_order IS 'Display order in admin selects and lists.';

CREATE TABLE IF NOT EXISTS public.office_rent_expense (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    office_id bigint NOT NULL,
    expense_month date NOT NULL,
    amount_nis numeric(14, 2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NULL,
    CONSTRAINT pk_office_rent_expense PRIMARY KEY (id),
    CONSTRAINT office_rent_expense_office_id_fkey
        FOREIGN KEY (office_id)
        REFERENCES public.rent_offices (id)
        ON DELETE RESTRICT,
    CONSTRAINT office_rent_expense_created_by_fkey
        FOREIGN KEY (created_by)
        REFERENCES auth.users (id)
        ON DELETE SET NULL,
    CONSTRAINT office_rent_expense_office_month_key
        UNIQUE (office_id, expense_month),
    CONSTRAINT office_rent_expense_amount_nis_chk
        CHECK (amount_nis >= 0),
    CONSTRAINT office_rent_expense_month_first_day_chk
        CHECK (date_trunc('month', expense_month::timestamp)::date = expense_month)
);

COMMENT ON TABLE public.office_rent_expense IS 'Monthly rent amount in NIS per office location.';
COMMENT ON COLUMN public.office_rent_expense.expense_month IS 'First calendar day of the month (YYYY-MM-01).';
COMMENT ON COLUMN public.office_rent_expense.amount_nis IS 'Rent amount in Israeli shekels (NIS).';

CREATE INDEX IF NOT EXISTS idx_office_rent_expense_office_id
    ON public.office_rent_expense (office_id);

CREATE INDEX IF NOT EXISTS idx_office_rent_expense_expense_month
    ON public.office_rent_expense (expense_month DESC);

CREATE INDEX IF NOT EXISTS idx_rent_offices_active_sort
    ON public.rent_offices (is_active, sort_order, name);

-- Seed initial offices
INSERT INTO public.rent_offices (name, sort_order)
VALUES
    ('Ramat Gan', 1),
    ('Jerusalem', 2)
ON CONFLICT (name) DO NOTHING;

CREATE OR REPLACE FUNCTION public.set_rent_offices_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.created_by IS NULL THEN
            NEW.created_by := auth.uid();
        END IF;
        IF NEW.created_at IS NULL THEN
            NEW.created_at := now();
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_rent_offices_audit ON public.rent_offices;
CREATE TRIGGER trg_rent_offices_audit
    BEFORE INSERT ON public.rent_offices
    FOR EACH ROW
    EXECUTE FUNCTION public.set_rent_offices_audit();

CREATE OR REPLACE FUNCTION public.set_office_rent_expense_audit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.created_by IS NULL THEN
            NEW.created_by := auth.uid();
        END IF;
        IF NEW.created_at IS NULL THEN
            NEW.created_at := now();
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_office_rent_expense_audit ON public.office_rent_expense;
CREATE TRIGGER trg_office_rent_expense_audit
    BEFORE INSERT ON public.office_rent_expense
    FOR EACH ROW
    EXECUTE FUNCTION public.set_office_rent_expense_audit();

ALTER TABLE public.rent_offices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.office_rent_expense ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "rent_offices_select" ON public.rent_offices;
CREATE POLICY "rent_offices_select" ON public.rent_offices FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "rent_offices_insert" ON public.rent_offices;
CREATE POLICY "rent_offices_insert" ON public.rent_offices FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "rent_offices_update" ON public.rent_offices;
CREATE POLICY "rent_offices_update" ON public.rent_offices FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "rent_offices_delete" ON public.rent_offices;
CREATE POLICY "rent_offices_delete" ON public.rent_offices FOR DELETE TO authenticated USING (true);

DROP POLICY IF EXISTS "office_rent_expense_select" ON public.office_rent_expense;
CREATE POLICY "office_rent_expense_select" ON public.office_rent_expense FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "office_rent_expense_insert" ON public.office_rent_expense;
CREATE POLICY "office_rent_expense_insert" ON public.office_rent_expense FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "office_rent_expense_update" ON public.office_rent_expense;
CREATE POLICY "office_rent_expense_update" ON public.office_rent_expense FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "office_rent_expense_delete" ON public.office_rent_expense;
CREATE POLICY "office_rent_expense_delete" ON public.office_rent_expense FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.rent_offices TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.office_rent_expense TO authenticated;
