-- =============================================================================
-- Digital Power of Attorney (POA) feature
-- -----------------------------------------------------------------------------
-- Public, token-based POA documents that clients fill out and sign online.
-- A contact (leads_contact) can have multiple POAs of different types.
-- POAs are linked to either a new lead (leads.id, UUID) or a legacy lead
-- (leads_lead.id, BIGINT), in addition to the contact.
--
-- Access model (mirrors client portal / public proforma):
--   * Tables have RLS enabled.
--   * Public (anon) access goes ONLY through SECURITY DEFINER RPCs by secure_token.
--   * Staff (authenticated) manage POAs via authenticated-only RPCs.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. POA TYPES (templates / categories)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.poa_types (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key         TEXT NOT NULL UNIQUE,             -- machine key used by the frontend renderer
  name        TEXT NOT NULL,                    -- human-readable name (staff dropdown)
  language    TEXT NOT NULL DEFAULT 'en',       -- primary language: en / he / de
  direction   TEXT NOT NULL DEFAULT 'ltr',      -- ltr / rtl
  jurisdiction TEXT NULL,                       -- e.g. Germany / Austria / Israel
  description TEXT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order  INT NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.poa_types IS 'Power of Attorney template types (German citizenship, standard Hebrew, Austrian citizenship, etc.).';
COMMENT ON COLUMN public.poa_types.key IS 'Stable machine key matched by the frontend document renderer.';

-- Seed the four known POA types (idempotent).
INSERT INTO public.poa_types (key, name, language, direction, jurisdiction, description, sort_order)
VALUES
  ('german_citizenship', 'German Citizenship POA (Vollmacht)', 'de', 'ltr', 'Germany',
   'Power of attorney to the Bundesverwaltungsamt for German citizenship procedures (bilingual DE/EN).', 10),
  ('standard_hebrew', 'Standard POA (Hebrew)', 'he', 'rtl', 'Israel',
   'General Hebrew power of attorney authorizing the firm before Israeli authorities and the German/Austrian embassies.', 20),
  ('austrian_citizenship_standard', 'Austrian Citizenship POA (Standard)', 'en', 'ltr', 'Austria',
   'Power of attorney for an individual applicant in the Austrian citizenship procedure.', 30),
  ('austrian_citizenship_minor', 'Austrian Citizenship POA (Minor / Family)', 'en', 'ltr', 'Austria',
   'Power of attorney for an applicant and minor children in the Austrian citizenship procedure.', 40)
ON CONFLICT (key) DO UPDATE
  SET name = EXCLUDED.name,
      language = EXCLUDED.language,
      direction = EXCLUDED.direction,
      jurisdiction = EXCLUDED.jurisdiction,
      description = EXCLUDED.description,
      sort_order = EXCLUDED.sort_order;

-- -----------------------------------------------------------------------------
-- 2. POA DOCUMENTS (instances created per contact)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.poa_documents (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  secure_token  TEXT NOT NULL UNIQUE DEFAULT ('poa_' || replace(gen_random_uuid()::text, '-', '')),

  poa_type_id   BIGINT NOT NULL REFERENCES public.poa_types(id) ON DELETE RESTRICT,

  -- A POA always belongs to a contact, and to one of the two lead tables.
  contact_id    BIGINT NOT NULL REFERENCES public.leads_contact(id) ON DELETE CASCADE,
  new_lead_id   UUID NULL REFERENCES public.leads(id) ON DELETE SET NULL,
  legacy_lead_id BIGINT NULL REFERENCES public.leads_lead(id) ON DELETE SET NULL,

  status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'sent', 'viewed', 'signed', 'cancelled')),

  language      TEXT NULL,                         -- snapshot of the type language at creation

  -- Free-form, type-specific captured field values + base64 signature images.
  field_data    JSONB NOT NULL DEFAULT '{}'::jsonb,
  signatures    JSONB NOT NULL DEFAULT '{}'::jsonb,

  signer_name   TEXT NULL,
  signer_email  TEXT NULL,
  signed_pdf_path TEXT NULL,                        -- optional storage path of generated PDF

  created_by    TEXT NULL,                          -- staff identifier (auth uid / email)
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at       TIMESTAMPTZ NULL,
  viewed_at     TIMESTAMPTZ NULL,
  signed_at     TIMESTAMPTZ NULL,
  expires_at    TIMESTAMPTZ NULL
);

COMMENT ON TABLE public.poa_documents IS 'Power of Attorney instances created for a lead contact; filled and signed on a public link.';
COMMENT ON COLUMN public.poa_documents.secure_token IS 'Public token used in /poa/:token link.';
COMMENT ON COLUMN public.poa_documents.field_data IS 'Type-specific field values captured from the public form.';
COMMENT ON COLUMN public.poa_documents.signatures IS 'Base64 signature images keyed by signature field id.';

CREATE INDEX IF NOT EXISTS idx_poa_documents_contact ON public.poa_documents(contact_id);
CREATE INDEX IF NOT EXISTS idx_poa_documents_new_lead ON public.poa_documents(new_lead_id);
CREATE INDEX IF NOT EXISTS idx_poa_documents_legacy_lead ON public.poa_documents(legacy_lead_id);
CREATE INDEX IF NOT EXISTS idx_poa_documents_status ON public.poa_documents(status);

-- keep updated_at fresh
CREATE OR REPLACE FUNCTION public._poa_touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_poa_documents_touch ON public.poa_documents;
CREATE TRIGGER trg_poa_documents_touch
  BEFORE UPDATE ON public.poa_documents
  FOR EACH ROW EXECUTE FUNCTION public._poa_touch_updated_at();

-- -----------------------------------------------------------------------------
-- 3. RLS
-- -----------------------------------------------------------------------------
ALTER TABLE public.poa_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.poa_documents ENABLE ROW LEVEL SECURITY;

-- POA types are non-sensitive lookup data: readable by staff.
DROP POLICY IF EXISTS poa_types_select_auth ON public.poa_types;
CREATE POLICY poa_types_select_auth
  ON public.poa_types FOR SELECT TO authenticated
  USING (true);

-- POA documents: authenticated staff have full access; anon has NONE
-- (anon reaches data only through the SECURITY DEFINER RPCs below).
DROP POLICY IF EXISTS poa_documents_all_auth ON public.poa_documents;
CREATE POLICY poa_documents_all_auth
  ON public.poa_documents FOR ALL TO authenticated
  USING (true) WITH CHECK (true);

GRANT SELECT ON public.poa_types TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.poa_documents TO authenticated;

-- =============================================================================
-- 4. PUBLIC RPCs (anon) — by secure_token only
-- =============================================================================

-- Fetch a POA for the public signing page. Marks it as viewed the first time.
CREATE OR REPLACE FUNCTION public.poa_get_public(p_token TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_poa public.poa_documents;
  v_type public.poa_types;
  v_contact public.leads_contact;
BEGIN
  SELECT * INTO v_poa FROM public.poa_documents WHERE secure_token = p_token;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'POA not found');
  END IF;

  IF v_poa.status = 'cancelled' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'This power of attorney is no longer available.');
  END IF;

  IF v_poa.expires_at IS NOT NULL AND v_poa.expires_at < now() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'This power of attorney link has expired.');
  END IF;

  SELECT * INTO v_type FROM public.poa_types WHERE id = v_poa.poa_type_id;
  SELECT * INTO v_contact FROM public.leads_contact WHERE id = v_poa.contact_id;

  -- First view: flip pending/sent -> viewed
  IF v_poa.status IN ('pending', 'sent') THEN
    UPDATE public.poa_documents
      SET status = 'viewed', viewed_at = COALESCE(viewed_at, now())
      WHERE id = v_poa.id;
    v_poa.status := 'viewed';
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'poa', jsonb_build_object(
      'id', v_poa.id,
      'status', v_poa.status,
      'field_data', v_poa.field_data,
      'signatures', v_poa.signatures,
      'signer_name', v_poa.signer_name,
      'signer_email', v_poa.signer_email,
      'signed_at', v_poa.signed_at,
      'created_at', v_poa.created_at
    ),
    'type', jsonb_build_object(
      'id', v_type.id,
      'key', v_type.key,
      'name', v_type.name,
      'language', v_type.language,
      'direction', v_type.direction,
      'jurisdiction', v_type.jurisdiction,
      'description', v_type.description
    ),
    'contact', jsonb_build_object(
      'id', v_contact.id,
      'name', v_contact.name,
      'email', v_contact.email,
      'phone', v_contact.phone,
      'mobile', v_contact.mobile,
      'address', v_contact.address,
      'id_passport', v_contact.id_passport
    )
  );
END;
$$;

-- Submit (sign) a POA from the public page.
CREATE OR REPLACE FUNCTION public.poa_submit_public(
  p_token TEXT,
  p_field_data JSONB,
  p_signatures JSONB,
  p_signer_name TEXT DEFAULT NULL,
  p_signer_email TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_poa public.poa_documents;
BEGIN
  SELECT * INTO v_poa FROM public.poa_documents WHERE secure_token = p_token FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'POA not found');
  END IF;

  IF v_poa.status = 'cancelled' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'This power of attorney is no longer available.');
  END IF;

  IF v_poa.status = 'signed' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'This power of attorney was already signed.');
  END IF;

  IF v_poa.expires_at IS NOT NULL AND v_poa.expires_at < now() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'This power of attorney link has expired.');
  END IF;

  UPDATE public.poa_documents
    SET field_data = COALESCE(p_field_data, '{}'::jsonb),
        signatures = COALESCE(p_signatures, '{}'::jsonb),
        signer_name = COALESCE(NULLIF(trim(p_signer_name), ''), signer_name),
        signer_email = COALESCE(NULLIF(trim(p_signer_email), ''), signer_email),
        status = 'signed',
        signed_at = now()
    WHERE id = v_poa.id;

  RETURN jsonb_build_object('ok', true, 'id', v_poa.id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.poa_get_public(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.poa_submit_public(TEXT, JSONB, JSONB, TEXT, TEXT) TO anon, authenticated;

-- =============================================================================
-- 5. STAFF RPCs (authenticated)
-- =============================================================================

-- Create a POA for a contact and return the row (incl. secure_token).
CREATE OR REPLACE FUNCTION public.poa_create(
  p_contact_id BIGINT,
  p_poa_type_id BIGINT,
  p_new_lead_id UUID DEFAULT NULL,
  p_legacy_lead_id BIGINT DEFAULT NULL,
  p_prefill JSONB DEFAULT '{}'::jsonb,
  p_created_by TEXT DEFAULT NULL,
  p_expires_at TIMESTAMPTZ DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_type public.poa_types;
  v_id UUID;
  v_token TEXT;
BEGIN
  SELECT * INTO v_type FROM public.poa_types WHERE id = p_poa_type_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Unknown POA type');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.leads_contact WHERE id = p_contact_id) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Contact not found');
  END IF;

  INSERT INTO public.poa_documents (
    poa_type_id, contact_id, new_lead_id, legacy_lead_id,
    language, field_data, status, created_by, expires_at
  )
  VALUES (
    p_poa_type_id, p_contact_id, p_new_lead_id, p_legacy_lead_id,
    v_type.language, COALESCE(p_prefill, '{}'::jsonb), 'pending', p_created_by, p_expires_at
  )
  RETURNING id, secure_token INTO v_id, v_token;

  RETURN jsonb_build_object(
    'ok', true,
    'id', v_id,
    'secure_token', v_token,
    'poa_type_id', p_poa_type_id,
    'type_key', v_type.key,
    'type_name', v_type.name
  );
END;
$$;

-- List POAs for a contact (newest first), with type info.
CREATE OR REPLACE FUNCTION public.poa_list_for_contact(p_contact_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_rows JSONB;
BEGIN
  SELECT COALESCE(jsonb_agg(row_to_json(t)::JSONB ORDER BY t.created_at DESC), '[]'::JSONB)
  INTO v_rows
  FROM (
    SELECT
      d.id,
      d.secure_token,
      d.status,
      d.poa_type_id,
      pt.key AS type_key,
      pt.name AS type_name,
      pt.language AS type_language,
      d.signer_name,
      d.created_at,
      d.sent_at,
      d.viewed_at,
      d.signed_at,
      d.expires_at
    FROM public.poa_documents d
    INNER JOIN public.poa_types pt ON pt.id = d.poa_type_id
    WHERE d.contact_id = p_contact_id
  ) t;

  RETURN jsonb_build_object('ok', true, 'poas', v_rows);
END;
$$;

-- Mark a POA as sent (e.g. after copying / sending the link).
CREATE OR REPLACE FUNCTION public.poa_mark_sent(p_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.poa_documents
    SET status = CASE WHEN status = 'pending' THEN 'sent' ELSE status END,
        sent_at = COALESCE(sent_at, now())
    WHERE id = p_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'POA not found');
  END IF;
  RETURN jsonb_build_object('ok', true);
END;
$$;

-- Cancel a POA (kept for audit; link stops working).
CREATE OR REPLACE FUNCTION public.poa_cancel(p_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.poa_documents SET status = 'cancelled' WHERE id = p_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'POA not found');
  END IF;
  RETURN jsonb_build_object('ok', true);
END;
$$;

-- Hard-delete a POA (only when not signed).
CREATE OR REPLACE FUNCTION public.poa_delete(p_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_status TEXT;
BEGIN
  SELECT status INTO v_status FROM public.poa_documents WHERE id = p_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'POA not found');
  END IF;
  IF v_status = 'signed' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Cannot delete a signed POA. Cancel it instead.');
  END IF;
  DELETE FROM public.poa_documents WHERE id = p_id;
  RETURN jsonb_build_object('ok', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.poa_create(BIGINT, BIGINT, UUID, BIGINT, JSONB, TEXT, TIMESTAMPTZ) TO authenticated;
GRANT EXECUTE ON FUNCTION public.poa_list_for_contact(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.poa_mark_sent(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.poa_cancel(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.poa_delete(UUID) TO authenticated;

-- Allow staff to read the POA type list for the "create POA" dropdown.
GRANT EXECUTE ON FUNCTION public.poa_get_public(TEXT) TO anon, authenticated;
