-- Find all identity sequences (for columns using GENERATED BY DEFAULT AS IDENTITY)
-- These might have different names than regular sequences

SELECT 
    schemaname,
    tablename,
    attname as column_name,
    seqtypid::regtype as sequence_type,
    pg_get_serial_sequence(schemaname||'.'||tablename, attname) as sequence_name
FROM pg_attribute a
JOIN pg_class c ON a.attrelid = c.oid
JOIN pg_namespace n ON c.relnamespace = n.oid
WHERE a.attidentity IN ('a', 'd')  -- 'a' = ALWAYS, 'd' = BY DEFAULT
  AND n.nspname = 'public'
  AND c.relname IN ('leads_contact', 'lead_leadcontact', 'leads_lead')
ORDER BY tablename, attname;

-- Also check if there are any integer columns in these tables that might be causing issues
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN ('leads_contact', 'lead_leadcontact', 'leads_lead')
  AND data_type = 'integer'
ORDER BY table_name, column_name;

