-- Threaded comments on RMQ chat messages (visible to all participants).
-- Run in Supabase SQL editor after deployment.

CREATE TABLE IF NOT EXISTS public.rmq_message_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES public.conversations (id) ON DELETE CASCADE,
  message_id bigint NOT NULL REFERENCES public.messages (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  body text NOT NULL CHECK (char_length(trim(body)) > 0 AND char_length(body) <= 4000),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rmq_message_comments_conversation
  ON public.rmq_message_comments (conversation_id);

CREATE INDEX IF NOT EXISTS idx_rmq_message_comments_message
  ON public.rmq_message_comments (message_id);

CREATE INDEX IF NOT EXISTS idx_rmq_message_comments_user
  ON public.rmq_message_comments (user_id);

ALTER TABLE public.rmq_message_comments ENABLE ROW LEVEL SECURITY;

-- SELECT: any participant in the conversation can read all comments on messages in that chat
DROP POLICY IF EXISTS "rmq_msg_comments_select_participant" ON public.rmq_message_comments;
CREATE POLICY "rmq_msg_comments_select_participant"
  ON public.rmq_message_comments
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.conversation_participants cp
      WHERE cp.conversation_id = rmq_message_comments.conversation_id
        AND cp.user_id = (SELECT u.id FROM public.users u WHERE u.auth_id = auth.uid() LIMIT 1)
        AND cp.is_active = true
    )
  );

-- INSERT: participant can add a comment as themselves
DROP POLICY IF EXISTS "rmq_msg_comments_insert_participant" ON public.rmq_message_comments;
CREATE POLICY "rmq_msg_comments_insert_participant"
  ON public.rmq_message_comments
  FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = (SELECT u.id FROM public.users u WHERE u.auth_id = auth.uid() LIMIT 1)
    AND EXISTS (
      SELECT 1
      FROM public.conversation_participants cp
      WHERE cp.conversation_id = rmq_message_comments.conversation_id
        AND cp.user_id = (SELECT u.id FROM public.users u WHERE u.auth_id = auth.uid() LIMIT 1)
        AND cp.is_active = true
    )
    AND EXISTS (
      SELECT 1
      FROM public.messages m
      WHERE m.id = rmq_message_comments.message_id
        AND m.conversation_id = rmq_message_comments.conversation_id
        AND m.is_deleted = false
    )
  );

-- DELETE: author can delete own comment
DROP POLICY IF EXISTS "rmq_msg_comments_delete_own" ON public.rmq_message_comments;
CREATE POLICY "rmq_msg_comments_delete_own"
  ON public.rmq_message_comments
  FOR DELETE
  TO authenticated
  USING (
    user_id = (SELECT u.id FROM public.users u WHERE u.auth_id = auth.uid() LIMIT 1)
  );

GRANT SELECT, INSERT, DELETE ON public.rmq_message_comments TO authenticated;
GRANT ALL ON public.rmq_message_comments TO service_role;

COMMENT ON TABLE public.rmq_message_comments IS 'Private-thread style comments on a chat message; visible to all conversation participants.';
