-- Per-user pinned messages inside an RMQ conversation (stable across sessions/devices).
-- Run in Supabase SQL editor after deployment.

CREATE TABLE IF NOT EXISTS public.rmq_user_pinned_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  conversation_id bigint NOT NULL REFERENCES public.conversations (id) ON DELETE CASCADE,
  message_id bigint NOT NULL REFERENCES public.messages (id) ON DELETE CASCADE,
  pinned_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rmq_user_pinned_messages_user_conv_msg UNIQUE (user_id, conversation_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_rmq_user_pinned_messages_user_conv
  ON public.rmq_user_pinned_messages (user_id, conversation_id);

CREATE INDEX IF NOT EXISTS idx_rmq_user_pinned_messages_message
  ON public.rmq_user_pinned_messages (message_id);

ALTER TABLE public.rmq_user_pinned_messages ENABLE ROW LEVEL SECURITY;

-- Helper: current app user id (public.users.id)
-- Policies use subselect on users.auth_id = auth.uid()

DROP POLICY IF EXISTS "rmq_pins_select_own" ON public.rmq_user_pinned_messages;
CREATE POLICY "rmq_pins_select_own"
  ON public.rmq_user_pinned_messages
  FOR SELECT
  TO authenticated
  USING (
    user_id = (SELECT u.id FROM public.users u WHERE u.auth_id = auth.uid() LIMIT 1)
  );

DROP POLICY IF EXISTS "rmq_pins_insert_own_participant" ON public.rmq_user_pinned_messages;
CREATE POLICY "rmq_pins_insert_own_participant"
  ON public.rmq_user_pinned_messages
  FOR INSERT
  TO authenticated
  WITH CHECK (
    user_id = (SELECT u.id FROM public.users u WHERE u.auth_id = auth.uid() LIMIT 1)
    AND EXISTS (
      SELECT 1
      FROM public.conversation_participants cp
      WHERE cp.conversation_id = rmq_user_pinned_messages.conversation_id
        AND cp.user_id = (SELECT u.id FROM public.users u WHERE u.auth_id = auth.uid() LIMIT 1)
        AND cp.is_active = true
    )
  );

DROP POLICY IF EXISTS "rmq_pins_delete_own" ON public.rmq_user_pinned_messages;
CREATE POLICY "rmq_pins_delete_own"
  ON public.rmq_user_pinned_messages
  FOR DELETE
  TO authenticated
  USING (
    user_id = (SELECT u.id FROM public.users u WHERE u.auth_id = auth.uid() LIMIT 1)
  );

GRANT SELECT, INSERT, DELETE ON public.rmq_user_pinned_messages TO authenticated;
GRANT ALL ON public.rmq_user_pinned_messages TO service_role;

COMMENT ON TABLE public.rmq_user_pinned_messages IS 'Which messages a user pinned in which RMQ conversation (personal, not shared with other participants).';
